# Group Project 2:  Financial Data Modeling and Database Implementation

## Part II: Database Creation

Making sure ipython-sql and psycopg2 libraries are installed so that we can use PostgreSQL.

In [1]:
!pip freeze | grep -E 'ipython-sql|psycopg2'

ipython-sql==0.4.1
psycopg2==2.9.5
psycopg2-binary==2.9.5


Dropping DB named SECDB (using PostgreSQL's dropdp command) if it already exists to ensure that this notebook can be run repeatedly.

In [2]:
!dropdb -U student SECDB

Using PostgreSQL's createdb command to create a database named SECDB

In [3]:
!createdb -U student SECDB

We want to utilize the query tools that SQL provides. To do so, we are installing the SQL extension to be able to run SQL in this notebook.

In [4]:
%load_ext sql

Connecting the SECDB database that we just created using the student user.

In [5]:
%sql postgresql://student@/SECDB

### Creating Tables

#### Creating SUB Table
Use DROP TABLE command before creating the table SUB. This is good practice in case table SUB already exists and allows us to run the notebook repeatedly. 

Use CREATE TABLE command to create table SUB that contains each entity and specifies the data type of each entity (and whether or not the column can take null values).

The SUB table does not contain any foreign keys. It does however contain a **primary key**, ADSH, which is referenced by other tables. ADSH uniquely identifies each row of SUB.

In [6]:
%%sql
DROP TABLE IF EXISTS SUB Cascade;

CREATE TABLE SUB (
    ADSH        VARCHAR(20) NOT NULL,
    CIK         NUMERIC(10,0) NOT NULL,
    NAME        VARCHAR(150) NOT NULL,
    SIC         NUMERIC(4,0) NULL,
    COUNTRYBA   VARCHAR(2) NOT NULL,
    STPRBA      VARCHAR(2) NULL,
    CITYBA      VARCHAR(30) NOT NULL,
    ZIPBA       VARCHAR(10) NULL,
    BAS1        VARCHAR(40) NULL,
    BAS2        VARCHAR(40) NULL,
    BAPH        VARCHAR(20) NULL,
    COUNTRYMA   VARCHAR(2) NULL,
    STPRMA      VARCHAR(2) NULL,
    CITYMA      VARCHAR(30) NULL,
    ZIPMA       VARCHAR(10) NULL,
    MAS1        VARCHAR(40) NULL,
    MAS2        VARCHAR(40) NULL,
    COUNTRYINC  VARCHAR(2) NOT NULL,
    STPRINC     VARCHAR(2) NULL,
    EIN         NUMERIC(10,0) NULL,
    FORMER      VARCHAR(150) NULL,
    CHANGED     VARCHAR(8) NULL,
    AFS         VARCHAR(5) NULL,
    WKSI        BOOLEAN NOT NULL,
    FYE         VARCHAR(4) NOT NULL,
    FORM        VARCHAR(10) NOT NULL,
    PERIOD      DATE NOT NULL,
    FY          NUMERIC(4,0) NOT NULL,
    FP          VARCHAR(2) NOT NULL,
    FILED       DATE NOT NULL,
    ACCEPTED    TIMESTAMP NOT NULL,
    PREVRPT     BOOLEAN NOT NULL,
    DETAIL      BOOLEAN NOT NULL,
    INSTANCE    VARCHAR(32) NOT NULL,
    NCIKS       NUMERIC(4,0) NOT NULL,
    ACIKS       VARCHAR(120) NULL,
    PUBFLOATUSD    NUMERIC(8,0) NULL,
    FLOATDATE   DATE NULL,
    FLOATAXIS   VARCHAR(255) NULL,
    FLOATMEMS   NUMERIC(1,0) NULL,

    PRIMARY KEY (ADSH)
);

 * postgresql://student@/SECDB
Done.
Done.


[]

Adding a comment to table SUB

In [7]:
%%sql
COMMENT ON TABLE SUB IS
'SUB table: Submission data set includes one record for each XBRL submission. The set includes fields of information pertinent to the submission and the filing entity';

 * postgresql://student@/SECDB
Done.


[]

Adding comments for each column of SUB

In [8]:
%%sql
COMMENT ON COLUMN SUB.adsh IS 'adsh: is an accession number, a 20-character string formed from the 18-digit number assigned by the Commission to each EDGAR submission. Where the 20, is the max-size in length that the column can have and the value is NOT NULL because all the columns contain valid entries. adsh is classified as CHAR because the value is in fixed length';
COMMENT ON COLUMN SUB.cik IS 'cik: is Central Index Key (CIK) assigned by the Commission to each registrant. cik is classified as NUMERIC (10,0) because it makes it explicit that only integers (whole numbers) are stored in this column and precision (10) is the total number of digits the number can have. The max-size length is 10 and the value is NOT NULL because all the columns contain valid entries';
COMMENT ON COLUMN SUB.name IS 'name: name of the registrant (legal entity) as recorded in EDGAR as of the filing date. name is classified as VARCHAR because it is not fixed in length but its max-size in length is 150. The value is NOT NULL because all the columns contain valid entries';
COMMENT ON COLUMN SUB.sic IS 'sic: Standard Industrial Classification (SIC) code assigned by the Commission, indicating the registrant''s type of business. sic is classified as NUMERIC (4,0) because it makes it explicit that only integers (whole numbers) are stored in this column and precision (4) is the total number of digits the number can have. The max-size length is 4. The value is NULL because allowing the SIC column to be NULL provides flexibility in situations where the SIC code is not available, applicable, or required';
COMMENT ON COLUMN SUB.countryba IS 'countryba: ISO 3166-1 country code of the registrant''s business address. countryba is classified as VARCHAR because the table in the Financial Statement specifies its ALPHANUMERIC. The max-size length is 2 and the value is NOT NULL because all the columns contain valid entries';
COMMENT ON COLUMN SUB.stprba IS 'stprba: State or province of the registrant''s business address (if COUNTRYBA is US or CA). stprba is classified as VARCHAR because the table in the Financial Statement specifies its ALPHANUMERIC. The max-size length is 2 and the value is NULL because there may be cases where a registrant in the US or CA does not provide a specific state or province, rendering the field optional or incomplete';
COMMENT ON COLUMN SUB.cityba IS 'cityba: City of the registrant''s business address. cityba is classified as VARCHAR because the table in the Financial Statement specifies its ALPHANUMERIC and there is no fixed length in the column. The max-size length is 30 and the value is NOT NULL because all the columns contain valid entries';
COMMENT ON COLUMN SUB.zipba IS 'zipba: Zip code of the registrant''s business address. zipba is classified as VARCHAR because the table in the Financial Statement specifies its ALPHANUMERIC and there is no fixed length in the column. The max-size length is 10 and the value is NULL because even though the cityba is NOT NULL, meaning a city must always be provided, the zipba could still be NULL if the zip code was missing, incomplete, or incorrectly formatted during data entry';
COMMENT ON COLUMN SUB.bas1 IS 'bas1: First line of the street of the registrant''s business address. bas1 is classified as VARCHAR because the table in the Financial Statement specifies its ALPHANUMERIC and there is no fixed length in the column. The max-size length is 40. The value is NULL because some of the first line of the registrant''s business address may not be provided or left incomplete during data entry';
COMMENT ON COLUMN SUB.bas2 IS 'bas2: Second line of the street of the registrant''s business address. bas2 is classified as VARCHAR because the table in the Financial Statement specifies its ALPHANUMERIC and there is no fixed length in the column. The max-size length is 40. The value is NULL because some of the second line of the registrant''s business address may not be provided or left incomplete during data entry';
COMMENT ON COLUMN SUB.baph IS 'baph: Phone number of the registrant''s business address. baph is classified as VARCHAR because the table in the Financial Statement specifies its ALPHANUMERIC and there is no fixed length in the column. The max-size length is 20. The value is NULL because some of the phone number of the registrant''s business address may not be provided or left incomplete during data entry';
COMMENT ON COLUMN SUB.countryma IS 'countryma: ISO 3166-1 country code of the registrant''s mailing address. countryma is classified as VARCHAR because the table in the Financial Statement specifies its ALPHANUMERIC and there is no fixed length in the column. The max-size length is 2. The value is NULL because some of ISO 3166-1 country code of the registrant''s mailing address may not be provided or left incomplete during data entry';
COMMENT ON COLUMN SUB.stprma IS 'stprma: State or province of the registrant''s mailing address (if COUNTRYMA is US or CA). stprma is classified as VARCHAR because the table in the Financial Statement specifies its ALPHANUMERIC and there is no fixed length in the column. The max-size length is 2. The value is NULL because some of state or province of the registrant''s mailing address may not be provided or left incomplete during data entry';
COMMENT ON COLUMN SUB.cityma IS 'cityma: City of the registrant''s mailing address. cityma is classified as VARCHAR because the table in the Financial Statement specifies its ALPHANUMERIC and there is no fixed length in the column. The max-size length is 30. The value is NULL because some of city of the registrant''s mailing address may not be provided or left incomplete during data entry';
COMMENT ON COLUMN SUB.zipma IS 'zipma: Zip code of the registrant''s mailing addres. zipma is classified as VARCHAR because the table in the Financial Statement specifies its ALPHANUMERIC and there is no fixed length in the column. The max-size length is 10. The value is NULL because some of zipcode of the registrant''s mailing address may not be provided or left incomplete during data entry';
COMMENT ON COLUMN SUB.mas1 IS 'mas1: First line of the street of the registrant''s mailing address. mas1 is classified as VARCHAR because the table in the Financial Statement specifies its ALPHANUMERIC and there is no fixed length in the column. The max-size length is 40. The value is NULL because some of the first line of the street of the registrant''s mailing address may not be provided or left incomplete during data entry';
COMMENT ON COLUMN SUB.mas2 IS 'mas2: Second line of the street of the registrant''s mailing address. mas2 is classified as VARCHAR because the table in the Financial Statement specifies its ALPHANUMERIC and there is no fixed length in the column. The max-size length is 40. The value is NULL because some of the second line of the street of the registrant''s mailing address may not be provided or left incomplete during data entry';
COMMENT ON COLUMN SUB.countryinc IS 'countryinc: Country of incorporation for the registrant (ISO 3166-1 ALPHA 2). countryinc is classified as VARCHAR because the table in the Financial Statement specifies its ALPHANUMERIC. The max-size length is 3 and the value is NOT NULL because all the columns contain valid entries';
COMMENT ON COLUMN SUB.stprinc IS 'stprinc:  State or province of incorporation for the registrant (if COUNTRYINC is US or CA). stprinc is classified as VARCHAR because the table in the Financial Statement specifies its ALPHANUMERIC and there is no fixed length in the column. The max-size length is 2. The value is NULL because some of the state or province of incorporation for the registrant may not be provided or left incomplete during data entry';
COMMENT ON COLUMN SUB.ein IS 'ein:  Employee Identification Number (EIN) assigned by the IRS to business entities operating in the US. ein is classified as NUMERIC (10,0) because it makes it explicit that only integers (whole numbers) are stored in this column and precision (10) is the total number of digits the number can have. The max-size length is 10. The value is NULL because some of the EIN may not be provided or left incomplete during data entry';
COMMENT ON COLUMN SUB.former IS 'former: Most recent former name of the registrant, if any. former is classified as VARCHAR because the table in the Financial Statement specifies its ALPHANUMERIC and there is no fixed length in the column. The max-size length is 150. The value is NULL because some of the most recent former name of the registrant may not be provided or left incomplete during data entry. There can also be cases where there isn''t any';
COMMENT ON COLUMN SUB.changed IS 'changed: Date of change from the former name, if any. changed is classified as VARCHAR because the table in the Financial Statement specifies its ALPHANUMERIC and there is no fixed length in the column. The max-size length is 8. The value is NULL because some of date may not have been provided or left incomplete during data entry. There can also be cases where there isn''t any';
COMMENT ON COLUMN SUB.afs IS 'afs: Filer status with the Commission at the time of submission (e.g., LAF, ACC, SRA, NON, SML). afs is classified as VARCHAR because the table in the Financial Statement specifies its ALPHANUMERIC and there is no fixed length in the column. The max-size length is 5. The value is NULL because some of filer status may not have been provided or left incomplete during data entry';
COMMENT ON COLUMN SUB.wksi IS 'wksi: Well Known Seasoned Issuer (WKSI) status; TRUE if the issuer meets specific Commission requirements. afs is classified as BOOLEAN because it indicates a binary state, typically representing whether a business entity qualifies as a Well-Known Seasoned Issuer or not, which can only be true or false (1 or 0). The max-size length is 1. The value is NOT NULL because all the columns contain valid entries';
COMMENT ON COLUMN SUB.fye IS 'fye: Fiscal Year End Date (format: MMDD). fye is classified as VARCHAR because the table in the Financial Statement specifies its ALPHANUMERIC and there is no fixed length in the column. The max-size length is 4. The value is NOT NULL because all the columns contain valid entries';
COMMENT ON COLUMN SUB.form IS 'form: The submission type of the registrant''s filing (e.g., 10-K, 10-Q). form is classified as VARCHAR because the table in the Financial Statement specifies its ALPHANUMERIC and there is no fixed length in the column. The max-size length is 10. The value is NOT NULL because all the columns contain valid entries';
COMMENT ON COLUMN SUB.period IS 'period: Balance Sheet Date (format: YYYY-MM-DD). period is classified as DATE because it stores the value as (yymmdd) in the column. The max-size length is 8. The value is NOT NULL because all the columns contain valid entries';
COMMENT ON COLUMN SUB.fy IS 'fy: Fiscal Year Focus (the year of the financial report). fy is classified as NUMERIC because it stores the value as (yyyy) in the column. The max-size length is 4. The value is NOT NULL because all the columns contain valid entries';
COMMENT ON COLUMN SUB.fp IS 'fp: Fiscal Period Focus (indicating the reporting period, e.g., FY, Q1, Q2). fp is classified as VARCHAR because the table in the Financial Statement specifies its ALPHANUMERIC and there is no fixed length in the column. The max-size length is 2. The value is NOT NULL because all the columns contain valid entries';
COMMENT ON COLUMN SUB.filed IS 'filed: The date of the registrant''s filing with the Commission. filed is classified as DATE because it stores the value as (yymmdd) in the column. The max-size length is 8. The value is NOT NULL because all the columns contain valid entries';
COMMENT ON COLUMN SUB.accepted IS 'accepted: The acceptance date and time of the registrant''s filing; filings accepted after 5:30pm EST are considered filed the next business day. accepted is classified as DATETIME because it is stored like this: (yyyy-mm-dd hh:mm:ss) in the column. The maz-size length is 19. The value is NOT NULL because all the columns contain valid entries';
COMMENT ON COLUMN SUB.prevrpt IS 'prevrpt: TRUE indicates that the submission information was subsequently amended prior to the end cutoff date of the data set. prevrpt is classified as boolean because it represents a binary condition, where the value indicates whether the submission information has been amended (1 for true) or not amended (0 for false). The max-size length is 1. The value is NOT NULL because all the columns contain valid entries';
COMMENT ON COLUMN SUB.detail IS 'detail: TRUE indicates that the XBRL submission contains quantitative disclosures within the footnotes and schedules at the required detail level. detail is classified as BOOLEAN because it indicates whether the XBRL submission includes quantitative disclosures at the required detail level, with 1 representing true (it does) and 0 representing false (it does not). The max-size length is 1. The value is NOT NULL because all the columns contain valid entries';
COMMENT ON COLUMN SUB.instance IS 'instance: Name of the submitted XBRL Instance Document (EX-101.INS) type data file, often beginning with the company. instance is classified as VARCHAR because the table in the Financial Statement specifies its ALPHANUMERIC and there is no fixed length in the column. The max-size length is 32. The value is NOT NULL because all the columns contain valid entries';
COMMENT ON COLUMN SUB.nciks IS 'nciks: Number of Central Index Keys (CIK) of registrants (i.e., business units) included in the consolidating entity''s submitted filing. nciks is classified as NUMERIC (4,0) because it makes it explicit that only integers (whole numbers) are stored in this column and precision (4) is the total number of digits the number can have. The max-size length is 4. The value is NOT NULL because all the columns contain valid entries';
COMMENT ON COLUMN SUB.aciks IS 'aciks: Additional CIKs of co-registrants included in a consolidating entity''s EDGAR submission, separated by spaces. aciks is classified as VARCHAR because the table in the Financial Statement specifies its ALPHANUMERIC and there is no fixed length in the column. The max-size length is 120. The value is NULL because if there are no other coregistrants (i.e., nciks = 1), the value of aciks is NULl';
COMMENT ON COLUMN SUB.pubfloatusd IS 'pubfloatusd: Public float, in USD, if provided in this submission. pubfloatusd is classified as NUMERIC (14,0) because it makes it explicit that only integers (whole numbers) are stored in this column and precision (14) is the total number of digits the number can have. The max-size length is 8. The pubfloatusd field may be null because the public float value was not disclosed or provided in the submission';
COMMENT ON COLUMN SUB.floatdate IS 'floatdate: Date on which the public float was measured by the filer. floatdate is classified as DATE because it stores the value as (yymmdd) in the column. The max-size length is 8. The value is NULL because The floatdate field may be null because the filer did not specify the date on which the public float was measured';
COMMENT ON COLUMN SUB.floataxis IS 'floataxis: If the public float value was computed by summing across several tagged values, this indicates the nature of the summation. floataxis is classified as VARCHAR because the table in the Financial Statement specifies its ALPHANUMERIC and there is no fixed length in the column. The max-size length is 255.The floataxis field may be null because some values may not be provided or left incomplete during data entry';
COMMENT ON COLUMN SUB.floatmems IS 'floatmems: Public float, in USD, if provided in this submission. floatmems is classified as NUMERIC (1,0) because it makes it explicit that only integers (whole numbers) are stored in this column and precision (1) is the total number of digits the number can have. The max-size length is 1. The field may be null because the some values may not be provided or left incomplete during data entry';

 * postgresql://student@/SECDB
Done.
Done.
Done.
Done.
Done.
Done.
Done.
Done.
Done.
Done.
Done.
Done.
Done.
Done.
Done.
Done.
Done.
Done.
Done.
Done.
Done.
Done.
Done.
Done.
Done.
Done.
Done.
Done.
Done.
Done.
Done.
Done.
Done.
Done.
Done.
Done.
Done.
Done.
Done.
Done.


[]

Retrieve table comment using pg_class

In [9]:
%%sql
SELECT obj_description(oid, 'pg_class')
FROM pg_class
WHERE upper(relname) = 'SUB';

 * postgresql://student@/SECDB
1 rows affected.


[('SUB table: Submission data set includes one record for each XBRL submission. The set includes fields of information pertinent to the submission and the filing entity',)]

Retrieve column comments using information_schema.columns and pg_class system views

In [10]:
%%sql
SELECT cols.column_name,
pg_catalog.col_description(c.oid, cols.ordinal_position::int)
FROM pg_catalog.pg_class c, information_schema.columns cols
 WHERE cols.table_name = c.relname  and upper(relname) = 'SUB';

 * postgresql://student@/SECDB
40 rows affected.


[('adsh', 'adsh: is an accession number, a 20-character string formed from the 18-digit number assigned by the Commission to each EDGAR submission. Where the 20 ... (40 characters truncated) ... umn can have and the value is NOT NULL because all the columns contain valid entries. adsh is classified as CHAR because the value is in fixed length'),
 ('cik', 'cik: is Central Index Key (CIK) assigned by the Commission to each registrant. cik is classified as NUMERIC (10,0) because it makes it explicit that  ... (74 characters truncated) ...  is the total number of digits the number can have. The max-size length is 10 and the value is NOT NULL because all the columns contain valid entries'),
 ('name', 'name: name of the registrant (legal entity) as recorded in EDGAR as of the filing date. name is classified as VARCHAR because it is not fixed in length but its max-size in length is 150. The value is NOT NULL because all the columns contain valid entries'),
 ('sic', "sic: Standard Industrial Classification (SIC) code assigned by the Commission, indicating the registrant's type of business. sic is classified as NUM ... (203 characters truncated) ... ue is NULL because allowing the SIC column to be NULL provides flexibility in situations where the SIC code is not available, applicable, or required"),
 ('countryba', "countryba: ISO 3166-1 country code of the registrant's business address. countryba is classified as VARCHAR because the table in the Financial Statement specifies its ALPHANUMERIC. The max-size length is 2 and the value is NOT NULL because all the columns contain valid entries"),
 ('stprba', "stprba: State or province of the registrant's business address (if COUNTRYBA is US or CA). stprba is classified as VARCHAR because the table in the F ... (96 characters truncated) ... cause there may be cases where a registrant in the US or CA does not provide a specific state or province, rendering the field optional or incomplete"),
 ('cityba', "cityba: City of the registrant's business address. cityba is classified as VARCHAR because the table in the Financial Statement specifies its ALPHANUMERIC and there is no fixed length in the column. The max-size length is 30 and the value is NOT NULL because all the columns contain valid entries"),
 ('zipba', "zipba: Zip code of the registrant's business address. zipba is classified as VARCHAR because the table in the Financial Statement specifies its ALPHA ... (148 characters truncated) ... ing a city must always be provided, the zipba could still be NULL if the zip code was missing, incomplete, or incorrectly formatted during data entry"),
 ('bas1', "bas1: First line of the street of the registrant's business address. bas1 is classified as VARCHAR because the table in the Financial Statement speci ... (86 characters truncated) ... is 40. The value is NULL because some of the first line of the registrant's business address may not be provided or left incomplete during data entry"),
 ('bas2', "bas2: Second line of the street of the registrant's business address. bas2 is classified as VARCHAR because the table in the Financial Statement spec ... (88 characters truncated) ... s 40. The value is NULL because some of the second line of the registrant's business address may not be provided or left incomplete during data entry"),
 ('baph', "baph: Phone number of the registrant's business address. baph is classified as VARCHAR because the table in the Financial Statement specifies its ALP ... (76 characters truncated) ...  20. The value is NULL because some of the phone number of the registrant's business address may not be provided or left incomplete during data entry"),
 ('countryma', "countryma: ISO 3166-1 country code of the registrant's mailing address. countryma is classified as VARCHAR because the table in the Financial Stateme ... (101 characters truncated) ... he value is NULL because some of ISO 3166-1 country code of the registrant's mailing address may not be provided or left incomplete d

#### Creating DIM Table
Use DROP TABLE command before creating the table DIM. 

Use CREATE TABLE command to create table DIM that contains each entity and specifies the data type of each entity (and whether or not the column can take null values).

DIM also does not contain any foreign key but does contain the **primary key**, DIMHASH, which is used by the NUM table to reference DIM. DIMHASH uniquely identifies each row of DIM.

In [11]:
%%sql
DROP TABLE IF EXISTS DIM Cascade;

CREATE TABLE DIM (
    DIMHASH VARCHAR(32) NOT NULL,
    SEGMENTS VARCHAR(1024) NOT NULL,
    SEGT BOOLEAN NOT NULL,

    PRIMARY KEY (DIMHASH)
);

 * postgresql://student@/SECDB
Done.
Done.


[]

Adding comment to table DIM

In [12]:
%%sql
COMMENT ON TABLE DIM IS
'DIM table: The DIM set contains all of the combinations of XBRL axis and member used to tag any submission';

 * postgresql://student@/SECDB
Done.


[]

Adding comments to each column of DIM

In [13]:
%%sql
COMMENT ON COLUMN DIM.dimhash IS 'dimhash: MD5 hash of the segments field text, used as a unique identifier for dimension information. dimh is classified as VARCHAR because it represents a string of characters generated by the MD5 hash function, which is expressed in hexadecimal format. The maz-size in length is 32. The value is NOT NULL because all the columns contain valid entries';
COMMENT ON COLUMN DIM.segments IS 'segments: Concatenation of tag names representing the axis and members appearing in the XBRL segments. segments is classified as VARCHAR because the table in the Financial Statement specifies its ALPHANUMERIC and there is no fixed length in the column. The maz-size in length is 1024. The value is NOT NULL because all the columns contain valid entries';
COMMENT ON COLUMN DIM.segt IS 'segt: TRUE if the segments field would have been longer than 1024 characters had it not been truncated, otherwise FALSE. segt is classified as BOOLEAN because it indicates whether the segments field was truncated due to exceeding 1024 characters, with TRUE representing that it was truncated and FALSE indicating it was not. The maz-size in length is 1. The value is NOT NULL because all the columns contain valid entries';

 * postgresql://student@/SECDB
Done.
Done.
Done.


[]

Retrieve table comment using pg_class 

In [14]:
%%sql
SELECT obj_description(oid, 'pg_class')
FROM pg_class
WHERE upper(relname) = 'DIM';

 * postgresql://student@/SECDB
1 rows affected.


[('DIM table: The DIM set contains all of the combinations of XBRL axis and member used to tag any submission',)]

Retrieve column comments using information_schema.columns and pg_class system views

In [15]:
%%sql
SELECT cols.column_name,
pg_catalog.col_description(c.oid, cols.ordinal_position::int)
FROM pg_catalog.pg_class c, information_schema.columns cols
 WHERE cols.table_name = c.relname  and upper(relname) = 'DIM';

 * postgresql://student@/SECDB
3 rows affected.


[('dimhash', 'dimhash: MD5 hash of the segments field text, used as a unique identifier for dimension information. dimh is classified as VARCHAR because it represe ... (53 characters truncated) ... function, which is expressed in hexadecimal format. The maz-size in length is 32. The value is NOT NULL because all the columns contain valid entries'),
 ('segments', 'segments: Concatenation of tag names representing the axis and members appearing in the XBRL segments. segments is classified as VARCHAR because the  ... (54 characters truncated) ... MERIC and there is no fixed length in the column. The maz-size in length is 1024. The value is NOT NULL because all the columns contain valid entries'),
 ('segt', 'segt: TRUE if the segments field would have been longer than 1024 characters had it not been truncated, otherwise FALSE. segt is classified as BOOLEA ... (123 characters truncated) ... at it was truncated and FALSE indicating it was not. The maz-size in length is 1. The value is NOT NULL because all the columns contain valid entries')]

#### Creating TAG Table
Use DROP TABLE command before creating the table TAG. 

Use CREATE TABLE command to create table TAG that contains each entity and specifies the data type of each entity (and whether or not the column can take null values).

TAG also does not contain any foreign key but does contain a **primary key** which consists of a combination of TAG and VERSION which uniquely identifies each row in TAG. The entity TAG is referenced by both NUM and PRE through keys TAG and VERSION.

In [16]:
%%sql
DROP TABLE IF EXISTS TAG Cascade;

CREATE TABLE TAG (
    tag VARCHAR(256) NOT NULL,
    version VARCHAR(20) NOT NULL,
    custom BOOLEAN NOT NULL,
    abstract BOOLEAN NOT NULL,
    datatype VARCHAR(20) NULL,
    iord VARCHAR(1) NOT NULL,
    crdr VARCHAR(1) NULL,
    tlabel VARCHAR(512) NULL,
    doc VARCHAR(2048) NULL,

    PRIMARY KEY (tag, version)
);

 * postgresql://student@/SECDB
Done.
Done.


[]

Adding comment to table TAG

In [17]:
%%sql
COMMENT ON TABLE TAG IS
'TAG table: The TAG data set contains all standard taxonomy tags, not just those appearing in submissions to date, and also includes all custom taxonomy tags defined in the submissions'; 

 * postgresql://student@/SECDB
Done.


[]

Adding comments to each column of TAG

In [18]:
%%sql
COMMENT ON COLUMN TAG.tag IS 'tag: The unique identifier (name) for a tag in a specific taxonomy release. tag is classified as VARCHAR because the table in the Financial Statement specifies its ALPHANUMERIC and there is no fixed length in the column. The max-size in length is 256. The value is NOT NULL because all the columns contain valid entries';
COMMENT ON COLUMN TAG.version IS 'version: Identifier for the taxonomy version; if a standard tag, it indicates the taxonomy of origin. version is classified as VARCHAR because the table in the Financial Statement specifies its ALPHANUMERIC and there is no fixed length in the column. The max-size in length is 20. The value is NOT NULL because all the columns contain valid entries';
COMMENT ON COLUMN TAG.custom IS 'custom: Indicates if the tag is custom (TRUE) or standard (FALSE). The custom field is classified as boolean because it indicates whether a tag is custom (1 for true) or standard (0 for false).  The max-size in length is 1. The value is NOT NULL because all the columns contain valid entries';
COMMENT ON COLUMN TAG.abstract IS 'abstract: Indicates if the tag is abstract (TRUE) and not used to represent a numeric fact. The abstract field is classified as boolean because it signifies whether the tag is not used to represent a numeric fact, with 1 indicating true (it is abstract) and 0 indicating false (it is not abstract). The max-size in length is 1. The value is NOT NULL because all the columns contain valid entries';
COMMENT ON COLUMN TAG.datatype IS 'datatype: Data type of the tag (e.g., monetary); NULL if the tag is abstract. datatype is classified as VARCHAR because the table in the Financial Statement specifies its ALPHANUMERIC and there is no fixed length in the column. The max-size in length is 20. The value is NULL because if abstract=1, then NULL';
COMMENT ON COLUMN TAG.iord IS 'iord: Indicates if the value is a point in time ("I") or a duration ("D"); NULL if the tag is abstract. iord is classified as VARCHAR because the table in the Financial Statement specifies its ALPHANUMERIC and there is no fixed length in the column. The max-size in length is 1. The value is NULL because if abstract=1, then NULL';
COMMENT ON COLUMN TAG.crdr IS 'crdr: The natural accounting balance of the tag ("C" for credit or "D" for debit); NULL if not defined. crdr is classified as VARCHAR because the table in the Financial Statement specifies its ALPHANUMERIC and there is no fixed length in the column. The max-size in length is 1. The value is NULL because if it''s not defined then NULL';
COMMENT ON COLUMN TAG.tlabel IS 'tlabel: The label text provided by the taxonomy for standard tags, or the text provided by the filer for custom tags. tlabel is classified as VARCHAR because the table in the Financial Statement specifies its ALPHANUMERIC and there is no fixed length in the column. The max-size in length is 512. The value is NULL because if a tag which had neither would have been a NULL value in the colunmn';
COMMENT ON COLUMN TAG.doc IS 'doc: Detailed definition for the tag, truncated to 2048 characters; may be from the taxonomy or provided by the filer. doc is classified as VARCHAR because the table in the Financial Statement specifies its ALPHANUMERIC and there is no fixed length in the column. The max-size in length is 2048. The value is NULL because some some tags have neither in which case the fielde is NULL in the column';

 * postgresql://student@/SECDB
Done.
Done.
Done.
Done.
Done.
Done.
Done.
Done.
Done.


[]

Retrieve table comment using pg_class

In [19]:
%%sql
SELECT obj_description(oid, 'pg_class')
FROM pg_class
WHERE upper(relname) = 'TAG';

 * postgresql://student@/SECDB
1 rows affected.


[('TAG table: The TAG data set contains all standard taxonomy tags, not just those appearing in submissions to date, and also includes all custom taxonomy tags defined in the submissions',)]

Retrieve column comments using information_schema.columns and pg_class system views

In [20]:
%%sql
SELECT cols.column_name,
pg_catalog.col_description(c.oid, cols.ordinal_position::int)
FROM pg_catalog.pg_class c, information_schema.columns cols
 WHERE cols.table_name = c.relname  and upper(relname) = 'TAG';

 * postgresql://student@/SECDB
9 rows affected.


[('tag', 'tag: The unique identifier (name) for a tag in a specific taxonomy release. tag is classified as VARCHAR because the table in the Financial Statement ... (21 characters truncated) ... UMERIC and there is no fixed length in the column. The max-size in length is 256. The value is NOT NULL because all the columns contain valid entries'),
 ('version', 'version: Identifier for the taxonomy version; if a standard tag, it indicates the taxonomy of origin. version is classified as VARCHAR because the ta ... (50 characters truncated) ... NUMERIC and there is no fixed length in the column. The max-size in length is 20. The value is NOT NULL because all the columns contain valid entries'),
 ('custom', 'custom: Indicates if the tag is custom (TRUE) or standard (FALSE). The custom field is classified as boolean because it indicates whether a tag is custom (1 for true) or standard (0 for false).  The max-size in length is 1. The value is NOT NULL because all the columns contain valid entries'),
 ('abstract', 'abstract: Indicates if the tag is abstract (TRUE) and not used to represent a numeric fact. The abstract field is classified as boolean because it si ... (97 characters truncated) ... stract) and 0 indicating false (it is not abstract). The max-size in length is 1. The value is NOT NULL because all the columns contain valid entries'),
 ('datatype', 'datatype: Data type of the tag (e.g., monetary); NULL if the tag is abstract. datatype is classified as VARCHAR because the table in the Financial St ... (10 characters truncated) ... ecifies its ALPHANUMERIC and there is no fixed length in the column. The max-size in length is 20. The value is NULL because if abstract=1, then NULL'),
 ('iord', 'iord: Indicates if the value is a point in time ("I") or a duration ("D"); NULL if the tag is abstract. iord is classified as VARCHAR because the tab ... (31 characters truncated) ... pecifies its ALPHANUMERIC and there is no fixed length in the column. The max-size in length is 1. The value is NULL because if abstract=1, then NULL'),
 ('crdr', 'crdr: The natural accounting balance of the tag ("C" for credit or "D" for debit); NULL if not defined. crdr is classified as VARCHAR because the tab ... (37 characters truncated) ... es its ALPHANUMERIC and there is no fixed length in the column. The max-size in length is 1. The value is NULL because if it\'s not defined then NULL'),
 ('tlabel', 'tlabel: The label text provided by the taxonomy for standard tags, or the text provided by the filer for custom tags. tlabel is classified as VARCHAR ... (95 characters truncated) ... length in the column. The max-size in length is 512. The value is NULL because if a tag which had neither would have been a NULL value in the colunmn'),
 ('doc', 'doc: Detailed definition for the tag, truncated to 2048 characters; may be from the taxonomy or provided by the filer. doc is classified as VARCHAR b ... (98 characters truncated) ... h in the column. The max-size in length is 2048. The value is NULL because some some tags have neither in which case the fielde is NULL in the column')]

#### Creating NUM Table
Use DROP TABLE command before creating the table NUM. 

Use CREATE TABLE command to create table NUM that contains each entity and specifies the data type of each entity (and whether or not the column can take null values).

The **primary key** of NUM consists of a combination of ADSH, TAG, VERSION, DDATE, QTRS, UOM, DIMH, and IPRX which uniquely identifies each row in NUM. 

NUM contains **foreign keys** ADSH, TAG, VERSION, and DIMHASH. ADSH on it's own references rows in SUB, the combination of TAG and VERSION references rows in the TAG table, and DIMH references the attribute DIMHASH in the DIM table.

In [21]:
%%sql
DROP TABLE IF EXISTS NUM Cascade;

CREATE TABLE NUM (
  ADSH    VARCHAR(20) NOT NULL,
  TAG     VARCHAR(256) NOT NULL,
  VERSION VARCHAR(20) NOT NULL,
  DDATE   DATE NOT NULL,
  QTRS    NUMERIC(8,0) NOT NULL,
  UOM     VARCHAR(20) NOT NULL,
  DIMH    VARCHAR(32) NOT NULL,
  IPRX    NUMERIC(2,0) NOT NULL,
  VALUE   NUMERIC(16,0) NULL,
  FOOTNOTE VARCHAR (512) NULL,
  FOOTLEN NUMERIC(4,0) NOT NULL,
  DIMN    NUMERIC(1,0) NOT NULL,
  COREG   VARCHAR(256) NULL,
  DURP    NUMERIC NOT NULL,
  DATP    NUMERIC(4) NOT NULL,
  DCML    NUMERIC(2,0) NOT NULL,

  PRIMARY KEY (ADSH, TAG, VERSION, DDATE, QTRS, UOM, DIMH, IPRX),
  
  FOREIGN KEY (ADSH) REFERENCES SUB(ADSH),
  FOREIGN KEY (TAG, VERSION) REFERENCES TAG(TAG, VERSION),
  FOREIGN KEY (DIMH) REFERENCES DIM(DIMHASH)

);

 * postgresql://student@/SECDB
Done.
Done.


[]

Adding comment to table NUM

In [22]:
%%sql
COMMENT ON TABLE NUM IS
'NUM table: The NUM data set contains numeric data, one row per data point in the financial statements';

 * postgresql://student@/SECDB
Done.


[]

Adding comments to each column of NUM

In [23]:
%%sql
COMMENT ON COLUMN NUM.adsh IS 'adsh: is an accession number, a 20-character string formed from the 18-digit number assigned by the Commission to each EDGAR submission. Where the 20, is the max-size in length that the column can have and the value is NOT NULL because all the columns contain valid entries. adsh is classified as CHAR because the value is in fixed length';
COMMENT ON COLUMN NUM.tag IS 'tag: The unique identifier (name) for a tag in a specific taxonomy release. tag is classified as VARCHAR because the table in the Financial Statement specifies its ALPHANUMERIC and there is no fixed length in the column. The max-size in length is 256. The value is NOT NULL because all the columns contain valid entries';
COMMENT ON COLUMN NUM.version IS 'version: For a standard tag, it''s an identifier for the taxonomy;otherwise the accession number where the tag was defined. version is classified as VARCHAR because the table in the Financial Statement specifies its ALPHANUMERIC and there is no fixed length in the column. The max-size in length is 20. The value is NOT NULL because all the columns contain valid entries';
COMMENT ON COLUMN NUM.ddate IS 'ddate: The end date for the data value, rounded to the nearest month end (format: YYYY-MM-DD). ddate is classified as DATE because it stores the value as (yymmdd) in the column. The maz-size length is 8. The value is NOT NULL because all the columns contain valid entries';
COMMENT ON COLUMN NUM.qtrs IS 'qtrs: The count of the number of quarters represented by the data value, rounded to the nearest whole number. qtrs is classified as NUMERIC (8,0) because it makes it explicit that only integers (whole numbers) are stored in this column and precision (8) is the total number of digits the number can have. The max-size length is 8. The value is NOT NULL because all the columns contain valid entries';
COMMENT ON COLUMN NUM.uom IS 'uom: The unit of measure for the value (e.g., USD, shares). uom is classified as VARCHAR because the table in the Financial Statement specifies its ALPHANUMERIC and there is no fixed length in the column. The max-size in length is 20. The value is NOT NULL because all the columns contain valid entries';
COMMENT ON COLUMN NUM.dimh IS 'dimh: The 32-byte hexadecimal key for the dimensional information in the DIM data set. dimh is classified as VARCHAR because the table in the Financial Statement specifies its ALPHANUMERIC and there is no fixed length in the column. The max-size in length is 32. The value is NOT NULL because all the columns contain valid entries';
COMMENT ON COLUMN NUM.iprx IS 'iprx: A positive integer to distinguish different reported facts that otherwise would have the same primary key. iprx is classified as NUMERIC (2,0) because it makes it explicit that only integers (whole numbers) are stored in this column and precision (2) is the total number of digits the number can have. The max-size length is 8. The value is NOT NULL because all the columns contain valid entries';
COMMENT ON COLUMN NUM.value IS 'value: The actual numeric value reported in the financial statements, rounded to four decimal places. value is classified as NUMERIC (16,0) because it makes it explicit that only integers (whole numbers) are stored in this column and precision (16) is the total number of digits the number can have. The max-size length is 16. The value is NULL because there may be missing data points';
COMMENT ON COLUMN NUM.footnote IS 'footnote: The plain text of any superscripted footnotes on the value, if any, as shown on the statement page, truncated to 512 characters. footnote is classified as VARCHAR because the table in the Financial Statement specifies its ALPHANUMERIC and there is no fixed length in the column. The max-size in length is 512. The footnote field may be null because there were no superscripted footnotes associated with the value, indicating that no relevant text was provided in the submission';
COMMENT ON COLUMN NUM.footlen IS 'footlen: Number of bytes in the plain text of the footnote prior to truncation, indicating footnote length. footlen is classified as NUMERIC (4,0) because it makes it explicit that only integers (whole numbers) are stored in this column and precision (4) is the total number of digits the number can have. The max-size length is 4. The value is NOT NULL because all the columns contain valid entries';
COMMENT ON COLUMN NUM.dimn IS 'dimn: Small integer representing the number of dimensions associated with the reported value. dimn is classified as NUMERIC (1,0) because it makes it explicit that only integers (whole numbers) are stored in this column and precision (1) is the total number of digits the number can have. The max-size length is 4. The value is NOT NULL because all the columns contain valid entries';
COMMENT ON COLUMN NUM.coreg IS 'coreg: If specified, indicates a specific co-registrant, the parent company, or other entity; NULL indicates the consolidated entity. coreg is classified as VARCHAR because the table in the Financial Statement specifies its ALPHANUMERIC and there is no fixed length in the column. The max-size in length is 256. The value may be NULL because it was not specified in the submission, indicating that the entity is treated as a consolidated entity without a specific co-registrant or related party identified';
COMMENT ON COLUMN NUM.durp IS 'durp: The difference between the reported fact duration and the quarter duration, expressed as a fraction of 1. durp is classified as NUMERIC since it is a fraction of 1 and contains several digits after the decimal. Since these digits vary, the parameters for precision and scale are not specified. The max-size in length is 4. The value is NOT NULL because all the columns contain valid entries';
COMMENT ON COLUMN NUM.datp IS 'datp: The difference between the reported fact date and the month-end rounded date, expressed as a fraction of 1. datp is classified as NUMERIC (4) because it is a fraction of 1 with max-size in length of 4. It is not specified how many digits can be after the decimal, so we are not limitting the range by including a value for scale. The value is NOT NULL because all the columns contain valid entries';
COMMENT ON COLUMN NUM.dcml IS 'dcml: The value of the fact "decimals" attribute, with INF represented by 32767. dcml is classified as NUMERIC (2,0) because it makes it explicit that only integers (whole numbers) are stored in this column and precision (2) is the total number of digits the number can have. The max-size length is 2. The value is NOT NULL because all the columns contain valid entries';

 * postgresql://student@/SECDB
Done.
Done.
Done.
Done.
Done.
Done.
Done.
Done.
Done.
Done.
Done.
Done.
Done.
Done.
Done.
Done.


[]

Retrieve table comment using pg_class

In [24]:
%%sql
SELECT obj_description(oid, 'pg_class')
FROM pg_class
WHERE upper(relname) = 'NUM';

 * postgresql://student@/SECDB
1 rows affected.


[('NUM table: The NUM data set contains numeric data, one row per data point in the financial statements',)]

Retrieve column comments using information_schema.columns and pg_class system views

In [25]:
%%sql
SELECT cols.column_name,
pg_catalog.col_description(c.oid, cols.ordinal_position::int)
FROM pg_catalog.pg_class c, information_schema.columns cols
 WHERE cols.table_name = c.relname  and upper(relname) = 'NUM';

 * postgresql://student@/SECDB
16 rows affected.


[('adsh', 'adsh: is an accession number, a 20-character string formed from the 18-digit number assigned by the Commission to each EDGAR submission. Where the 20 ... (40 characters truncated) ... umn can have and the value is NOT NULL because all the columns contain valid entries. adsh is classified as CHAR because the value is in fixed length'),
 ('tag', 'tag: The unique identifier (name) for a tag in a specific taxonomy release. tag is classified as VARCHAR because the table in the Financial Statement ... (21 characters truncated) ... UMERIC and there is no fixed length in the column. The max-size in length is 256. The value is NOT NULL because all the columns contain valid entries'),
 ('version', "version: For a standard tag, it's an identifier for the taxonomy;otherwise the accession number where the tag was defined. version is classified as V ... (71 characters truncated) ... NUMERIC and there is no fixed length in the column. The max-size in length is 20. The value is NOT NULL because all the columns contain valid entries"),
 ('ddate', 'ddate: The end date for the data value, rounded to the nearest month end (format: YYYY-MM-DD). ddate is classified as DATE because it stores the value as (yymmdd) in the column. The maz-size length is 8. The value is NOT NULL because all the columns contain valid entries'),
 ('qtrs', 'qtrs: The count of the number of quarters represented by the data value, rounded to the nearest whole number. qtrs is classified as NUMERIC (8,0) bec ... (100 characters truncated) ...  (8) is the total number of digits the number can have. The max-size length is 8. The value is NOT NULL because all the columns contain valid entries'),
 ('uom', 'uom: The unit of measure for the value (e.g., USD, shares). uom is classified as VARCHAR because the table in the Financial Statement specifies its A ... (4 characters truncated) ... NUMERIC and there is no fixed length in the column. The max-size in length is 20. The value is NOT NULL because all the columns contain valid entries'),
 ('dimh', 'dimh: The 32-byte hexadecimal key for the dimensional information in the DIM data set. dimh is classified as VARCHAR because the table in the Financi ... (32 characters truncated) ... NUMERIC and there is no fixed length in the column. The max-size in length is 32. The value is NOT NULL because all the columns contain valid entries'),
 ('iprx', 'iprx: A positive integer to distinguish different reported facts that otherwise would have the same primary key. iprx is classified as NUMERIC (2,0)  ... (103 characters truncated) ...  (2) is the total number of digits the number can have. The max-size length is 8. The value is NOT NULL because all the columns contain valid entries'),
 ('value', 'value: The actual numeric value reported in the financial statements, rounded to four decimal places. value is classified as NUMERIC (16,0) because i ... (87 characters truncated) ... ecision (16) is the total number of digits the number can have. The max-size length is 16. The value is NULL because there may be missing data points'),
 ('footnote', 'footnote: The plain text of any superscripted footnotes on the value, if any, as shown on the statement page, truncated to 512 characters. footnote i ... (189 characters truncated) ...  may be null because there were no superscripted footnotes associated with the value, indicating that no relevant text was provided in the submission'),
 ('footlen', 'footlen: Number of bytes in the plain text of the footnote prior to truncation, indicating footnote length. footlen is classified as NUMERIC (4,0) be ... (101 characters truncated) ...  (4) is the total number of digits the number can have. The max-size length is 4. The value is NOT NULL because all the columns contain valid entries'),
 ('dimn', 'dimn: Small integer representing the number of dimensions associated with the reported value. dimn is classified as NUMERIC (1,0) because it makes it ... (84 characters truncated) ...  (1) is the total number o

#### Creating PRE Table
Use DROP TABLE command before creating the table PRE. 

Use CREATE TABLE command to create table PRE that contains each entity and specifies the data type of each entity (and whether or not the column can take null values).

The **primary key** of PRE consists of a combination of ADSH, REPORT, AND LINE which uniquely identifies each row in PRE. 

NUM contains **foreign keys** ADSH, TAG, and VERSION. ADSH on it's own references rows in SUB, the combination of TAG and VERSION references rows in the TAG table, and the combination of ADSH, TAG, and VERSION refereces rows in the NUM table in accordance with the notes on the data. We do not reference the combination of ADSH, TAG, and VERSION as a foreign key below when building the table for PRE because it is redundant given ADSH and the combination of TAG and PRE are already being used as foreign keys. Additionally, when including ADSH, TAG, and VERSION as a foreign key referencing NUM, we see the error message that this key combination is not unique in the NUM table and therefore cannot be used.

In [26]:
%%sql
DROP TABLE IF EXISTS PRE Cascade;

CREATE TABLE PRE (
    ADSH VARCHAR(20) NOT NULL,
    REPORT NUMERIC(6,0) NOT NULL,
    LINE NUMERIC(6,0) NOT NULL,
    STMT VARCHAR(2) NOT NULL,
    INPTH BOOLEAN NOT NULL,
    TAG VARCHAR(256) NOT NULL,
    VERSION VARCHAR(20) NOT NULL,
    PROLE VARCHAR(50) NOT NULL,
    PLABEL VARCHAR(512) NOT NULL,
    NEGATING BOOLEAN NOT NULL,

    PRIMARY KEY (ADSH, REPORT, LINE),
    
    FOREIGN KEY (ADSH) REFERENCES SUB(ADSH),
    FOREIGN KEY (TAG, VERSION) REFERENCES TAG(TAG, VERSION)
    
);

 * postgresql://student@/SECDB
Done.
Done.


[]

In [27]:
%%sql
COMMENT ON TABLE PRE IS
'PRE table: Presentation data set; this provides information about how the tags and numbers were presented in the primary financial statements';

 * postgresql://student@/SECDB
Done.


[]

In [28]:
%%sql
COMMENT ON COLUMN PRE.adsh IS 'adsh: is an accession number, a 20-character string formed from the 18-digit number assigned by the Commission to each EDGAR submission. Where the 20, is the max-size in length that the column can have and the value is NOT NULL because all the columns contain valid entries. adsh is classified as VARCHAR because the value is not fixed length';
COMMENT ON COLUMN PRE.report IS 'report: represents the report grouping, which is a numeric value referring to the "R file" as computed by the renderer. Where we have classified report as a numeric (6,0) because it contains whole numbers with max-length of 6 and no digits after the decimal. It is NOT NULL because all the columns contain valid entries';
COMMENT ON COLUMN PRE.line IS 'line: represents the tags presentation line order for a given report, allowing for the correct ordering of line items. Line is classified as anumeric (6,0) because it contains whole numbers with max-length of 6 and no digits after the decimal. It is NOT NULL because all the columns contain valid entries';
COMMENT ON COLUMN PRE.stmt IS ' stmt: the financial statement location to which the value of the "report" field pertains (e.g., CP for Cover Page, BS for Balance Sheet, IS = Income Statement, CF = Cash Flow, EQ = Equity, UN = Unclassifiable Statement). stmt is classified as a VARCHAR because the values are in fixed length. As seen in the table, the abbreviated words are shown in two letters only, "CP","BS".. hence why the max-size in length is also 2. The value is NOT NULL because all the columns contain valid entries'; 
COMMENT ON COLUMN PRE.inpth IS'inpth: 1 indicates whether the value was presented "parenthetically" instead of in fields within the financial statements. inpth is classified as a BOOLEAN field type because it represents a binary condition—either the value is presented parenthetically (1 or TRUE), or it is not (0 or FALSE). The value is NOT NULL because all the columns contain valid entries';
COMMENT ON COLUMN PRE.tag IS 'tag: the tag chosen by the filer for this line item, which corresponds to a specific taxonomy tag used in XBRL. tag is classified as VARCHAR because it is not fixed in length but its max-size in length is 256. The value is NOT NULL because all the columns contain valid entries';
COMMENT ON COLUMN PRE.version IS 'version: the taxonomy identifier if the tag is a standard tag; otherwise, it is the accession number where the tag was defined. version is classified as VARCHAR because it is not fixed in length but its max-size in length is 20. The value is NOT NULL because all the columns contain valid entries';
COMMENT ON COLUMN PRE.prole IS 'prole: the XBRL link "role" of the preferred label, indicating the role of the tag in the financial statement. prole is classified as VARCHAR because it is not fixed in legth but its max-size in length is 50. The value is NOT NULL because all the columns contain valid entries';
COMMENT ON COLUMN PRE.plabel IS 'plabel: the text presented on the line item, also known as a "preferred" label, which describes the financial data. plabel is classified as VARCHAR because it is not fixed in legth but its max-size in length is 512. The value is NOT NULL because all the columns contain valid entries';
COMMENT ON COLUMN PRE.negating IS 'negating: flag to indicate whether the prole is treated as negating by the renderer, affecting how the value is interpreted. This is classified as a BOOLEAN because it represents a binary state—either the profile is treated as negating by the renderer (TRUE or 1), or it is not (FALSE or 0). The value is NOT NULL because all the columns contain valid entries'; 

 * postgresql://student@/SECDB
Done.
Done.
Done.
Done.
Done.
Done.
Done.
Done.
Done.
Done.


[]

Retrieve table comment using pg_class

In [29]:
%%sql
SELECT obj_description(oid, 'pg_class')
FROM pg_class
WHERE upper(relname) = 'PRE';

 * postgresql://student@/SECDB
1 rows affected.


[('PRE table: Presentation data set; this provides information about how the tags and numbers were presented in the primary financial statements',)]

Retrieve column comments using information_schema.columns and pg_class system views

In [30]:
%%sql
SELECT cols.column_name,
pg_catalog.col_description(c.oid, cols.ordinal_position::int)
FROM pg_catalog.pg_class c, information_schema.columns cols
 WHERE cols.table_name = c.relname  and upper(relname) = 'PRE';

 * postgresql://student@/SECDB
10 rows affected.


[('adsh', 'adsh: is an accession number, a 20-character string formed from the 18-digit number assigned by the Commission to each EDGAR submission. Where the 20 ... (44 characters truncated) ... can have and the value is NOT NULL because all the columns contain valid entries. adsh is classified as VARCHAR because the value is not fixed length'),
 ('report', 'report: represents the report grouping, which is a numeric value referring to the "R file" as computed by the renderer. Where we have classified repo ... (21 characters truncated) ...  because it contains whole numbers with max-length of 6 and no digits after the decimal. It is NOT NULL because all the columns contain valid entries'),
 ('line', 'line: represents the tags presentation line order for a given report, allowing for the correct ordering of line items. Line is classified as anumeric ... (6 characters truncated) ...  because it contains whole numbers with max-length of 6 and no digits after the decimal. It is NOT NULL because all the columns contain valid entries'),
 ('stmt', ' stmt: the financial statement location to which the value of the "report" field pertains (e.g., CP for Cover Page, BS for Balance Sheet, IS = Income ... (194 characters truncated) ... hown in two letters only, "CP","BS".. hence why the max-size in length is also 2. The value is NOT NULL because all the columns contain valid entries'),
 ('inpth', 'inpth: 1 indicates whether the value was presented "parenthetically" instead of in fields within the financial statements. inpth is classified as a B ... (63 characters truncated) ... er the value is presented parenthetically (1 or TRUE), or it is not (0 or FALSE). The value is NOT NULL because all the columns contain valid entries'),
 ('tag', 'tag: the tag chosen by the filer for this line item, which corresponds to a specific taxonomy tag used in XBRL. tag is classified as VARCHAR because it is not fixed in length but its max-size in length is 256. The value is NOT NULL because all the columns contain valid entries'),
 ('version', 'version: the taxonomy identifier if the tag is a standard tag; otherwise, it is the accession number where the tag was defined. version is classified as VARCHAR because it is not fixed in length but its max-size in length is 20. The value is NOT NULL because all the columns contain valid entries'),
 ('prole', 'prole: the XBRL link "role" of the preferred label, indicating the role of the tag in the financial statement. prole is classified as VARCHAR because it is not fixed in legth but its max-size in length is 50. The value is NOT NULL because all the columns contain valid entries'),
 ('plabel', 'plabel: the text presented on the line item, also known as a "preferred" label, which describes the financial data. plabel is classified as VARCHAR because it is not fixed in legth but its max-size in length is 512. The value is NOT NULL because all the columns contain valid entries'),
 ('negating', 'negating: flag to indicate whether the prole is treated as negating by the renderer, affecting how the value is interpreted. This is classified as a  ... (61 characters truncated) ... le is treated as negating by the renderer (TRUE or 1), or it is not (FALSE or 0). The value is NOT NULL because all the columns contain valid entries')]

### Uploading Financial Data

#### Unzipping data for each month

Each of the monthly financial data files were downloaded and the zip files were uploaded to the directory '/home/ubuntu/notebooks'. 

In [31]:
!pwd

/home/ubuntu/notebooks


The code below is run to unzip each of monthly files.

In [33]:
!unzip 2024_01_notes.zip -d Jan2024

Archive:  2024_01_notes.zip
  inflating: Jan2024/sub.tsv         
  inflating: Jan2024/tag.tsv         
  inflating: Jan2024/dim.tsv         
  inflating: Jan2024/ren.tsv         
  inflating: Jan2024/cal.tsv         
  inflating: Jan2024/pre.tsv         
  inflating: Jan2024/num.tsv         
  inflating: Jan2024/txt.tsv         
  inflating: Jan2024/readme.htm      
  inflating: Jan2024/notes-metadata.json  


In [34]:
!unzip 2024_02_notes.zip -d Feb2024

Archive:  2024_02_notes.zip
  inflating: Feb2024/sub.tsv         
  inflating: Feb2024/tag.tsv         
  inflating: Feb2024/dim.tsv         
  inflating: Feb2024/ren.tsv         
  inflating: Feb2024/cal.tsv         
  inflating: Feb2024/pre.tsv         
  inflating: Feb2024/num.tsv         
  inflating: Feb2024/txt.tsv         
  inflating: Feb2024/readme.htm      
  inflating: Feb2024/notes-metadata.json  


In [35]:
!unzip 2024_03_notes.zip -d Mar2024

Archive:  2024_03_notes.zip
  inflating: Mar2024/sub.tsv         
  inflating: Mar2024/tag.tsv         
  inflating: Mar2024/dim.tsv         
  inflating: Mar2024/ren.tsv         
  inflating: Mar2024/cal.tsv         
  inflating: Mar2024/pre.tsv         
  inflating: Mar2024/num.tsv         
  inflating: Mar2024/txt.tsv         
  inflating: Mar2024/readme.htm      
  inflating: Mar2024/notes-metadata.json  


In [38]:
!unzip 2024_04_notes.zip -d Apr2024

Archive:  2024_04_notes.zip
  inflating: Apr2024/sub.tsv         
  inflating: Apr2024/tag.tsv         
  inflating: Apr2024/dim.tsv         
  inflating: Apr2024/ren.tsv         
  inflating: Apr2024/cal.tsv         
  inflating: Apr2024/pre.tsv         
  inflating: Apr2024/num.tsv         
  inflating: Apr2024/txt.tsv         
  inflating: Apr2024/readme.htm      
  inflating: Apr2024/notes-metadata.json  


#### Converting all tsv files into csv files for all entities

In [39]:
!csvformat -t ./Jan2024/sub.tsv > jan_sub.csv
!csvformat -t ./Feb2024/sub.tsv > feb_sub.csv
!csvformat -t ./Mar2024/sub.tsv > mar_sub.csv
!csvformat -t ./Apr2024/sub.tsv > apr_sub.csv

In [40]:
!csvformat -t ./Jan2024/tag.tsv > jan_tag.csv
!csvformat -t ./Feb2024/tag.tsv > feb_tag.csv
!csvformat -t ./Mar2024/tag.tsv > mar_tag.csv
!csvformat -t ./Apr2024/tag.tsv > apr_tag.csv

In [41]:
!csvformat -t ./Jan2024/dim.tsv > jan_dim.csv
!csvformat -t ./Feb2024/dim.tsv > feb_dim.csv
!csvformat -t ./Mar2024/dim.tsv > mar_dim.csv
!csvformat -t ./Apr2024/dim.tsv > apr_dim.csv

In [42]:
!csvformat -t ./Jan2024/pre.tsv > jan_pre.csv
!csvformat -t ./Feb2024/pre.tsv > feb_pre.csv
!csvformat -t ./Mar2024/pre.tsv > mar_pre.csv
!csvformat -t ./Apr2024/pre.tsv > apr_pre.csv

In [43]:
!csvformat -t ./Jan2024/num.tsv > jan_num.csv
!csvformat -t ./Feb2024/num.tsv > feb_num.csv
!csvformat -t ./Mar2024/num.tsv > mar_num.csv
!csvformat -t ./Apr2024/num.tsv > apr_num.csv

### Stacking files for each month into one csv file for each entity

!csvstack jan_sub.csv feb_sub.csv mar_sub.csv apr_sub.csv > final_sub.csv

!csvstack jan_tag.csv feb_tag.csv mar_tag.csv apr_tag.csv > final_tag.csv

!csvstack jan_dim.csv feb_dim.csv mar_dim.csv apr_dim.csv > final_dim.csv

!csvstack jan_pre.csv feb_pre.csv mar_pre.csv apr_pre.csv > final_pre.csv

!csvstack jan_num.csv feb_num.csv mar_num.csv apr_num.csv > final_num.csv

#### *IMPORTANT*
We worked on the data for all four months for each entity. In loading in the data to the tables we were able to do it for all four months up until NUM but since NUM data is very large we could execute the last code on NUM on our instances even after multiple attempts. Hence, we decided to work with two months data. Again, we faced issues with loading it in for NUM and had to come down to working on just one month Jan. We leave some of the code as markdowns to show our attempt to work on full data.

### Stacking CSV for two months (JAN and FEB 2024)

!csvstack jan_sub.csv feb_sub.csv > final_sub.csv

!csvstack jan_tag.csv feb_tag.csv > final_tag.csv

!csvstack jan_dim.csv feb_dim.csv > final_dim.csv

!csvstack jan_pre.csv feb_pre.csv > final_pre.csv

!csvstack jan_num.csv feb_num.csv > final_num.csv

## Loading data into the tables created for each attribute

### Loading SUB dataset into the SUB table

In [43]:
!head -n 1000 jan_sub.csv | csvstat

/home/ubuntu/.local/lib/python3.8/site-packages/agate/table/from_csv.py:74: RuntimeWarning: Error sniffing CSV dialect: Could not determine delimiter
  1. "adsh"

	Type of data:          Text
	Contains null values:  False
	Unique values:         999
	Longest value:         20 characters
	Most common values:    0000081061-24-000003 (1x)
	                       0000090168-23-000081 (1x)
	                       0000090168-23-000083 (1x)
	                       0000093410-24-000002 (1x)
	                       0000107140-24-000002 (1x)

  2. "cik"

	Type of data:          Number
	Contains null values:  False
	Unique values:         864
	Smallest value:        2186
	Largest value:         2006191
	Sum:                   1360083967
	Mean:                  1361445.412
	Median:                1498710
	StDev:                 506268.034
	Most common values:    216877 (6x)
	                       1325878 (5x)
	                       1029744 (4x)
	                       1564708 (4x)
	             

In [32]:
%%sql
COPY SUB FROM '/home/ubuntu/notebooks/jan_sub.csv'
CSV
HEADER;

 * postgresql://student@/SECDB
(psycopg2.errors.NotNullViolation) null value in column "fy" violates not-null constraint
DETAIL:  Failing row contains (0000081061-24-000003, 81061, PUBLIX SUPER MARKETS INC, 5411, US, FL, LAKELAND, 33811, 3300 PUBLIX CORPORATE PARKWAY, null, 863-688-1188, US, FL, LAKELAND, 33811, 3300 PUBLIX CORPORATE PARKWAY, null, US, FL, 590324412, null, null, 4-NON, f, 1231, 8-K, 2023-12-31, null, null, 2024-01-02, 2024-01-02 14:19:00, f, f, ck0000081061-20240101_htm.xml, 1, null, null, null, null, null).
CONTEXT:  COPY sub, line 2: "0000081061-24-000003,81061,PUBLIX SUPER MARKETS INC,5411,US,FL,LAKELAND,33811,3300 PUBLIX CORPORATE ..."

[SQL: COPY SUB FROM '/home/ubuntu/notebooks/jan_sub.csv'
CSV
HEADER;]
(Background on this error at: https://sqlalche.me/e/14/gkpj)


##### Explain error:
The error shows up for the "fy" or "Fiscal Year Focus" column. We looked through the dataset and found that there are more than one missing values in the "fy" column. When loading the data on the database SUB table it looks like it is considering the missing cells as NULL when trying to upload the data. This violates the constraint of "Not NULL" on the "fy" attribute and hence returns the error. 

##### Next Step:
We would try to update the constraint from "NOT NULL" to "NULL" and upload the data. The reason we take that approach is because when studying the data we found the "fy" field gives the fiscal year in focus. There already exists fields for fiscal year end date "fye" which gives the months and the balance sheet date "period" which gives the year month and date. It seems like making the field constraint null may not effect our analysis for the dataset. These values cannot be dropped since there are more missing fields in this column than filled in fields.

#### Updating the constraint on the attribute "fy" in SUB

In [33]:
%%sql

ALTER TABLE sub
ALTER COLUMN fy DROP NOT NULL;

 * postgresql://student@/SECDB
Done.


[]

#### Load data again

In [34]:
%%sql
COPY SUB FROM '/home/ubuntu/notebooks/jan_sub.csv'
CSV
HEADER;

 * postgresql://student@/SECDB
(psycopg2.errors.NotNullViolation) null value in column "fp" violates not-null constraint
DETAIL:  Failing row contains (0000081061-24-000003, 81061, PUBLIX SUPER MARKETS INC, 5411, US, FL, LAKELAND, 33811, 3300 PUBLIX CORPORATE PARKWAY, null, 863-688-1188, US, FL, LAKELAND, 33811, 3300 PUBLIX CORPORATE PARKWAY, null, US, FL, 590324412, null, null, 4-NON, f, 1231, 8-K, 2023-12-31, null, null, 2024-01-02, 2024-01-02 14:19:00, f, f, ck0000081061-20240101_htm.xml, 1, null, null, null, null, null).
CONTEXT:  COPY sub, line 2: "0000081061-24-000003,81061,PUBLIX SUPER MARKETS INC,5411,US,FL,LAKELAND,33811,3300 PUBLIX CORPORATE ..."

[SQL: COPY SUB FROM '/home/ubuntu/notebooks/jan_sub.csv'
CSV
HEADER;]
(Background on this error at: https://sqlalche.me/e/14/gkpj)


##### Error:
The "fp" column returns a similar error. We looked through the dataset and found most of the cells in this column of the dataset have missing values. The data is related to financial period in focus within fiscal year. 

#### Updating the constraint on the attribute "fp" in SUB

In [35]:
%%sql

ALTER TABLE sub
ALTER COLUMN fp DROP NOT NULL;

 * postgresql://student@/SECDB
Done.


[]

#### Try to load data again

In [36]:
%%sql
COPY SUB FROM '/home/ubuntu/notebooks/jan_sub.csv'
CSV
HEADER;

 * postgresql://student@/SECDB
(psycopg2.errors.NotNullViolation) null value in column "countryinc" violates not-null constraint
DETAIL:  Failing row contains (0000898173-24-000003, 898173, O REILLY AUTOMOTIVE INC, 5531, US, MO, SPRINGFIELD, 65802, 233 S PATTERSON AVE, null, 417-829-5878, US, MO, SPRINGFIELD, 65802, 233 S PATTERSON AVE, null, null, null, 274358837, null, null, 1-LAF, f, 1231, 8-K, 2023-12-31, null, null, 2024-01-02, 2024-01-02 16:32:00, f, f, orly-20240102x8k_htm.xml, 1, null, null, null, null, null).
CONTEXT:  COPY sub, line 11: "0000898173-24-000003,898173,O REILLY AUTOMOTIVE INC,5531,US,MO,SPRINGFIELD,65802,233 S PATTERSON AVE..."

[SQL: COPY SUB FROM '/home/ubuntu/notebooks/jan_sub.csv'
CSV
HEADER;]
(Background on this error at: https://sqlalche.me/e/14/gkpj)


##### Error:
The error in the countryinc column is because some rows in the column are empty. Since the constraint on the attribute is NOT NULL, while loading the data on the table its returning an error as the database system takes these missing values as NULL. 

To avoid this problem we will try to remove the constraint on "countryinc" and try to load the data. 

In [37]:
%%sql

ALTER TABLE sub
ALTER COLUMN countryinc DROP NOT NULL;

 * postgresql://student@/SECDB
Done.


[]

##### Try loading the data again

In [38]:
%%sql
COPY SUB FROM '/home/ubuntu/notebooks/jan_sub.csv'
CSV
HEADER;

 * postgresql://student@/SECDB
(psycopg2.errors.NotNullViolation) null value in column "fye" violates not-null constraint
DETAIL:  Failing row contains (0000950170-24-000306, 1484612, OUTSET MEDICAL, INC., 3845, US, CA, SAN JOSE, 95134, 3052 ORCHARD DRIVE, null, 669-231-8200, US, CA, SAN JOSE, 95134, 3052 ORCHARD DRIVE, null, US, DE, 200514392, HOME DIALYSIS PLUS, LTD., 20100219, 1-LAF, f, null, 8-K, 2023-12-31, null, null, 2024-01-02, 2024-01-02 16:41:00, f, f, om-20240102_htm.xml, 1, null, null, null, null, null).
CONTEXT:  COPY sub, line 31: "0000950170-24-000306,1484612,"OUTSET MEDICAL, INC.",3845,US,CA,SAN JOSE,95134,3052 ORCHARD DRIVE,,66..."

[SQL: COPY SUB FROM '/home/ubuntu/notebooks/jan_sub.csv'
CSV
HEADER;]
(Background on this error at: https://sqlalche.me/e/14/gkpj)


##### Error:
The error in the "fye" (Fiscal Year End Date) column is because the constraint is set to NOT NULL and there are a few missing rows in the column. While loading the data on the table, the database system treats the missing values as NULL and hence returns an error. 

We will try to fix this by dropping the constraint on this column.

In [39]:
%%sql

ALTER TABLE sub
ALTER COLUMN fye DROP NOT NULL;

 * postgresql://student@/SECDB
Done.


[]

##### Try loading the data again

In [40]:
%%sql
COPY SUB FROM '/home/ubuntu/notebooks/jan_sub.csv'
CSV
HEADER;

 * postgresql://student@/SECDB
(psycopg2.errors.NotNullViolation) null value in column "period" violates not-null constraint
DETAIL:  Failing row contains (0001193125-24-000495, 1949594, FIDELITY MULTI-STRATEGY CREDIT FUND, null, US, MA, BOSTON, 02110, 245 SUMMER STREET, null, 617-563-7000, US, MA, BOSTON, 02110, 245 SUMMER STREET, null, US, DE, 0, null, null, null, f, 0630, 424B3, null, null, null, 2024-01-02, 2024-01-02 12:23:00, f, f, d59653d424b3_htm.xml, 1, null, null, null, null, null).
CONTEXT:  COPY sub, line 102: "0001193125-24-000495,1949594,FIDELITY MULTI-STRATEGY CREDIT FUND,,US,MA,BOSTON,02110,245 SUMMER STRE..."

[SQL: COPY SUB FROM '/home/ubuntu/notebooks/jan_sub.csv'
CSV
HEADER;]
(Background on this error at: https://sqlalche.me/e/14/gkpj)


##### Error:
The error in the "period" (Balance Sheet Date) column is because the constraint is set to NOT NULL and there are a few missing rows in the column. While loading the data on the table, the database system treats the missing values as NULL and hence returns an error.

##### Next step:
We will try to fix this by dropping the constraint on this column. Since there are very few missing fields, we will try to impute these values once the data is successfully loaded.

In [41]:
%%sql

ALTER TABLE sub
ALTER COLUMN period DROP NOT NULL;

 * postgresql://student@/SECDB
Done.


[]

##### Try loading the data again

In [42]:
%%sql
COPY SUB FROM '/home/ubuntu/notebooks/jan_sub.csv'
CSV
HEADER;

 * postgresql://student@/SECDB
(psycopg2.errors.NotNullViolation) null value in column "countryba" violates not-null constraint
DETAIL:  Failing row contains (0001213900-24-001269, 1376231, VPR BRANDS, LP., 7372, null, null, null, null, null, null, 305-537-6607, US, FL, SUNRISE, 33323, 1141 SAWGRASS CORPORATE PARKWAY, null, null, null, 900191208, SOLEIL CAPITAL L.P., 20100401, 4-NON, f, 1231, 8-K, 2023-12-31, null, null, 2024-01-05, 2024-01-04 20:34:00, f, f, ea191186-8k_vprbrands_htm.xml, 1, null, null, null, null, null).
CONTEXT:  COPY sub, line 884: "0001213900-24-001269,1376231,"VPR BRANDS, LP.",7372,,,,,,,305-537-6607,US,FL,SUNRISE,33323,1141 SAWG..."

[SQL: COPY SUB FROM '/home/ubuntu/notebooks/jan_sub.csv'
CSV
HEADER;]
(Background on this error at: https://sqlalche.me/e/14/gkpj)


##### Error:
The error in the "countryba" (country of the registrant's business address) column is because the constraint is set to NOT NULL and there are a few missing rows in the column. While loading the data on the table, the database system treats the missing values as NULL and hence returns an error. 

##### Next Step:
We will try to fix this by dropping the constraint on this column. Since there are very few missing fields, we will try to drop these rows once the data is successfully loaded.

In [43]:
%%sql

ALTER TABLE sub
ALTER COLUMN countryba DROP NOT NULL;

 * postgresql://student@/SECDB
Done.


[]

##### Try loading in the data again

In [44]:
%%sql
COPY SUB FROM '/home/ubuntu/notebooks/jan_sub.csv'
CSV
HEADER;

 * postgresql://student@/SECDB
(psycopg2.errors.NotNullViolation) null value in column "cityba" violates not-null constraint
DETAIL:  Failing row contains (0001213900-24-001269, 1376231, VPR BRANDS, LP., 7372, null, null, null, null, null, null, 305-537-6607, US, FL, SUNRISE, 33323, 1141 SAWGRASS CORPORATE PARKWAY, null, null, null, 900191208, SOLEIL CAPITAL L.P., 20100401, 4-NON, f, 1231, 8-K, 2023-12-31, null, null, 2024-01-05, 2024-01-04 20:34:00, f, f, ea191186-8k_vprbrands_htm.xml, 1, null, null, null, null, null).
CONTEXT:  COPY sub, line 884: "0001213900-24-001269,1376231,"VPR BRANDS, LP.",7372,,,,,,,305-537-6607,US,FL,SUNRISE,33323,1141 SAWG..."

[SQL: COPY SUB FROM '/home/ubuntu/notebooks/jan_sub.csv'
CSV
HEADER;]
(Background on this error at: https://sqlalche.me/e/14/gkpj)


##### Error:
The error in the "cityba" (city of the registrant's business address) column is because the constraint is set to NOT NULL and there are a few missing rows in the column. While loading the data on the table, the database system treats the missing values as NULL and hence returns an error. 

##### Next Step:
We will try to fix this by dropping the constraint on this column. Since there are very few missing fields, we will try to drop these rows once the data is successfully loaded.¶

In [45]:
%%sql

ALTER TABLE sub
ALTER COLUMN cityba DROP NOT NULL;

 * postgresql://student@/SECDB
Done.


[]

##### Try loading in the data again

In [46]:
%%sql
COPY SUB FROM '/home/ubuntu/notebooks/jan_sub.csv'
CSV
HEADER;

 * postgresql://student@/SECDB
(psycopg2.errors.NumericValueOutOfRange) numeric field overflow
DETAIL:  A field with precision 8, scale 0 must round to an absolute value less than 10^8.
CONTEXT:  COPY sub, line 985, column pubfloatusd: "144946000.00"

[SQL: COPY SUB FROM '/home/ubuntu/notebooks/jan_sub.csv'
CSV
HEADER;]
(Background on this error at: https://sqlalche.me/e/14/9h9h)


##### Error:
The error above is on the "pubfloatusd" column because the column as float values whereas the constraint assigned in the table only alllows integers with upto 8 digits). 

##### Next Step:
The solution is to first increase the max size of the field as the maximum value is upto 13 digits and allow for digits to go upto 2 decimal places. We increase this if an error shows up with a field size exceeding that.

In [47]:
%%sql

ALTER TABLE sub
ALTER COLUMN pubfloatusd TYPE NUMERIC(12,2);

 * postgresql://student@/SECDB
Done.


[]

##### Try loading in the data again

In [48]:
%%sql
COPY SUB FROM '/home/ubuntu/notebooks/jan_sub.csv'
CSV
HEADER;

 * postgresql://student@/SECDB
(psycopg2.errors.NumericValueOutOfRange) numeric field overflow
DETAIL:  A field with precision 12, scale 2 must round to an absolute value less than 10^10.
CONTEXT:  COPY sub, line 2742, column pubfloatusd: "165530000000.00"

[SQL: COPY SUB FROM '/home/ubuntu/notebooks/jan_sub.csv'
CSV
HEADER;]
(Background on this error at: https://sqlalche.me/e/14/9h9h)


In [49]:
%%sql

ALTER TABLE sub
ALTER COLUMN pubfloatusd TYPE NUMERIC(15,2);

 * postgresql://student@/SECDB
Done.


[]

##### Try loading in the data again

In [50]:
%%sql
COPY SUB FROM '/home/ubuntu/notebooks/jan_sub.csv'
CSV
HEADER;

 * postgresql://student@/SECDB
5904 rows affected.


[]

In [51]:
!csvstat --count jan_sub.csv

5904


##### Data successfully loaded:
The rows from the Jan SUB csv file matches the number of rows loaded on the SUB table in the database which confirms that our data was successfully loaded.

##### Explain error: 
It looks the highest value in digits this column takes is upto 20 digits. So we update the constraint to cater to such values.

In [18]:
%%sql

ALTER TABLE sub
ALTER COLUMN pubfloatusd TYPE NUMERIC(20,2);

 * postgresql://student@/SECDB
Done.


[]

In [20]:
%%sql
COPY SUB FROM '/home/ubuntu/notebooks/Assignment2/final_sub.csv'
CSV
HEADER;

 * postgresql://student@/SECDB
(psycopg2.errors.NumericValueOutOfRange) numeric field overflow
DETAIL:  A field with precision 1, scale 0 must round to an absolute value less than 10^1.
CONTEXT:  COPY sub, line 14169, column floatmems: "16"

[SQL: COPY SUB FROM '/home/ubuntu/notebooks/Assignment2/final_sub.csv'
CSV
HEADER;]
(Background on this error at: https://sqlalche.me/e/14/9h9h)


##### Explain error:
The floatmems column (number of terms in the summation if the public float was computed) returns a constraint violation error as the max size is set to 1 whereas the summation can have more than 1 digit. We will try solving this by increasing the max-size of the field to 2.

In [19]:
%%sql

ALTER TABLE sub
ALTER COLUMN floatmems TYPE NUMERIC(2,0);

 * postgresql://student@/SECDB
Done.


[]

In [20]:
%%sql
COPY SUB FROM '/home/ubuntu/notebooks/Assignment2/final_sub.csv'
CSV
HEADER;

 * postgresql://student@/SECDB
15304 rows affected.


[]

In [3]:
!csvstat --count final_sub.csv

15304


##### The rows from the final SUB csv file matches the number of rows loaded on the SUB table in the database which confirms that our data was successfully loaded.

### Loading TAG dataset into the TAG table

In [64]:
!head -n 1000 jan_tag.csv | csvstat

  1. "tag"

	Type of data:          Text
	Contains null values:  False
	Unique values:         766
	Longest value:         116 characters
	Most common values:    AccountsPayableRelatedPartyCurrent (7x)
	                       AccountingPoliciesLineItems (6x)
	                       AccountingPoliciesTable (6x)
	                       A0.875NotesDue2025Member (5x)
	                       AccountingForWarrantsPolicyTextBlock (5x)

  2. "version"

	Type of data:          Text
	Contains null values:  False
	Unique values:         261
	Longest value:         20 characters
	Most common values:    0001035443-24-000072 (74x)
	                       us-gaap/2023 (70x)
	                       0000732712-24-000003 (29x)
	                       0000732712-24-000007 (29x)
	                       0001193125-24-013874 (29x)

  3. "custom"

	Type of data:          Boolean
	Contains null values:  False
	Unique values:         2
	Most common values:    True (900x)
	                       False (99x)

  

In [52]:
%%sql
COPY TAG FROM '/home/ubuntu/notebooks/jan_tag.csv'
CSV
HEADER;

 * postgresql://student@/SECDB
(psycopg2.errors.NotNullViolation) null value in column "iord" violates not-null constraint
DETAIL:  Failing row contains (A0.0001EUR1850Million20202028NovartisFinanceS.A.LuxembourgLuxemb..., 0001370368-24-000004, t, t, member, null, null, 0.000% 1 EUR 1 850 million 2020/2028 Novartis Finance S.A., Luxe..., null).
CONTEXT:  COPY tag, line 2: "A0.0001EUR1850Million20202028NovartisFinanceS.A.LuxembourgLuxembourgIssuedAt99.354Member,0001370368-..."

[SQL: COPY TAG FROM '/home/ubuntu/notebooks/jan_tag.csv'
CSV
HEADER;]
(Background on this error at: https://sqlalche.me/e/14/gkpj)


##### Error:
IORD is indicated as not being able to take null values in the notes to the financial statement with the exception that it can be null IF ABSTRACT=1. 

Because of this stipulation, we have updated the constraint to allow for IORD to take null values.

In [54]:
%%sql

ALTER TABLE tag
ALTER COLUMN iord DROP NOT NULL;

 * postgresql://student@/SECDB
Done.


[]

##### Try load in the data again

In [55]:
%%sql
COPY TAG FROM '/home/ubuntu/notebooks/jan_tag.csv'
CSV
HEADER;

 * postgresql://student@/SECDB
84276 rows affected.


[]

In [56]:
!wc -l /home/ubuntu/notebooks/jan_tag.csv

84277 /home/ubuntu/notebooks/jan_tag.csv


##### Data successfully loaded:
84277 rows in jan_tag.csv *including* the header for a total of 84276 rows of data. In table TAG, we see that there are also 84276 rows, validating that the counts of the csv match the counts in the database.

##### The error message above is occurring because some key combinations of version and tag occurs more than once across ALL months in the final_tag.csv. While the primary key is unique in each month, we find duplicates upon stacking. To verify that the data in each column of these rows remain consistent across each occurrence of these combinations, we ran the below code. From this we can see that these rows are perfect duplicates of each other. In this case, we see that this version tag combo occurs exactly 2 times, one for each month of data.

In [14]:
!grep 'AcceleratedShareRepurchasesAdjustmentToRecordedAmount', 'us-gaap/2023' /home/ubuntu/notebooks/final_tag.csv

grep: us-gaap/2023: No such file or directory
/home/ubuntu/notebooks/final_tag.csv:AcceleratedShareRepurchasesAdjustmentToRecordedAmount,us-gaap/2023,0,0,monetary,D,D,"Accelerated Share Repurchases, Adjustment to Recorded Amount","The adjustment needed to reconcile previously recorded amounts to the actual aggregate amount paid, whether in cash or other consideration, to acquire all of the shares purchased under an Accelerated Share Repurchase arrangement."
/home/ubuntu/notebooks/final_tag.csv:AcceleratedShareRepurchasesAdjustmentToRecordedAmount,us-gaap/2023,0,0,monetary,D,D,"Accelerated Share Repurchases, Adjustment to Recorded Amount","The adjustment needed to reconcile previously recorded amounts to the actual aggregate amount paid, whether in cash or other consideration, to acquire all of the shares purchased under an Accelerated Share Repurchase arrangement."


##### Creating a table, TAG1 that does not include primary key constraint. This allows us to upload the data without recieving the error about unique contraints.

In [22]:
%%sql
DROP TABLE IF EXISTS TAG1 Cascade;

CREATE TABLE TAG1 (
    TAG VARCHAR(256) NOT NULL,
    VERSION VARCHAR(20) NOT NULL,
    CUSTOM BOOLEAN NOT NULL,
    ABSTRACT BOOLEAN NOT NULL,
    DATATYPE VARCHAR(20) NULL,
    IORD VARCHAR(1) NULL,
    CRDR VARCHAR(1) NULL,
    TLABEL VARCHAR(512) NULL,
    DOC VARCHAR(2048) NULL
);

 * postgresql://student@/SECDB
Done.
Done.


[]

##### Verifying the number of rows in final_tag.csv

In [51]:
!wc -l /home/ubuntu/notebooks/Assignment2/final_tag.csv

619123 /home/ubuntu/notebooks/Assignment2/final_tag.csv


In [23]:
%%sql
COPY TAG1 FROM '/home/ubuntu/notebooks/Assignment2/final_tag.csv'
CSV
HEADER;

 * postgresql://student@/SECDB
619122 rows affected.


[]

##### 619123 rows in final_tag.csv *including* the header for a total of 619122 rows of data. In table TAG1, we see that there are also 619122 rows, validating that the counts of the csv match the counts in the database prior to dropping duplicate rows from the database.

##### We can use the DISTINCT feature to select only unique rows from TAG1 to be added to table TAG. We can then go ahead and alter the new TAG table to include the primary key combination of tag and version.

In [24]:
%%sql
DROP TABLE IF EXISTS TAG Cascade;
CREATE TABLE TAG AS
SELECT DISTINCT tag,version,custom,abstract,datatype,iord,crdr,tlabel,doc
FROM TAG1;

 * postgresql://student@/SECDB
Done.
608029 rows affected.


[]

In [25]:
%%sql
ALTER TABLE TAG ADD PRIMARY KEY (TAG, VERSION)

 * postgresql://student@/SECDB
Done.


[]

In [26]:
%%sql
DROP TABLE IF EXISTS TAG1 Cascade

 * postgresql://student@/SECDB
Done.


[]

##### Queries to determine if only NULL values for IORD exists when ABSTRACT=1.

In [8]:
%%sql
SELECT COUNT(ABSTRACT)
FROM TAG
WHERE IORD is NULL;

 * postgresql://student@/SECDB
1 rows affected.


[(274627,)]

In [10]:
%%sql
SELECT COUNT(ABSTRACT)
FROM TAG
WHERE IORD is NULL
AND ABSTRACT is TRUE;

 * postgresql://student@/SECDB
1 rows affected.


[(274627,)]

### Loading DIM dataset into the DIM table

In [57]:
%%sql
COPY DIM FROM '/home/ubuntu/notebooks/jan_dim.csv'
CSV
HEADER;

 * postgresql://student@/SECDB
(psycopg2.errors.StringDataRightTruncation) value too long for type character varying(32)
CONTEXT:  COPY dim, line 2, column dimhash: "0xef558142c09cb75426d7735bd81ecdde"

[SQL: COPY DIM FROM '/home/ubuntu/notebooks/jan_dim.csv'
CSV
HEADER;]
(Background on this error at: https://sqlalche.me/e/14/9h9h)


##### Error:
The initial varchar(32) constraint was too short for some of the incoming data. There are values that are more than 32 characters.

##### Next Step:
By increasing the length to 34 characters, we ensure that longer dimhash values can be stored without causing errors during data loading. This command alters the dimhash column to change its data type to varchar(34) in order to accommodate longer dimhash values.

In [58]:
%%sql

ALTER TABLE dim
ALTER COLUMN dimhash TYPE varchar(34);

 * postgresql://student@/SECDB
Done.


[]

##### Try loading data again

In [126]:
%%sql
COPY DIM FROM '/home/ubuntu/notebooks/jan_dim.csv'
CSV
HEADER;

 * postgresql://student@/SECDB
(psycopg2.errors.NotNullViolation) null value in column "segments" violates not-null constraint
DETAIL:  Failing row contains (0x00000000, null, f).
CONTEXT:  COPY dim, line 20896: "0x00000000,,0"

[SQL: COPY DIM FROM '/home/ubuntu/notebooks/jan_dim.csv'
CSV
HEADER;]
(Background on this error at: https://sqlalche.me/e/14/gkpj)


##### Error:
When running the COPY DIM FROM command, we encountered an error due to NULL values in the segments column, which has a NOT NULL constraint.

##### Next Step:
We had to alter the table to allow NULL values and successfully load the data.

In [59]:
%%sql

ALTER TABLE DIM
ALTER COLUMN segments DROP NOT NULL;

 * postgresql://student@/SECDB
Done.


[]

##### Try load the data again

In [60]:
%%sql

COPY DIM FROM '/home/ubuntu/notebooks/jan_dim.csv'
CSV
HEADER;

 * postgresql://student@/SECDB
43201 rows affected.


[]

In [61]:
!csvstat --count jan_dim.csv

43201


##### Data successfully loaded:
The rows from the Jan DIM csv file matches the number of rows loaded on the DIM table in the database which confirms that our data was successfully loaded.

##### Before copying the dim data into the dim table, we need to create a unique dim.csv file, as we encountered the error psycopg2.errors.UniqueViolation. This error occurs because the dimhash column has a uniqueness constraint, which ensures that no two rows in the dim table can have the same value for dimhash. Since we are loading the data for two months, the primary key might have the duplication for dimensions dataset. To resolve this, we used the command below to create another csv with unique dim values.

In [74]:
!{ head -n 1 final_dim.csv && tail -n +2 final_dim.csv | sort | uniq; } > unique_dim.csv

In [29]:
%%sql
COPY DIM FROM '/home/ubuntu/notebooks/Assignment2/unique_dim.csv'
CSV
HEADER;

 * postgresql://student@/SECDB
460390 rows affected.


[]

In [11]:
!csvstat --count unique_dim.csv

460390


### Loading NUM dataset into the NUM table

In [62]:
%%sql

COPY NUM FROM '/home/ubuntu/notebooks/jan_num.csv'
CSV
HEADER;

 * postgresql://student@/SECDB
(psycopg2.errors.StringDataRightTruncation) value too long for type character varying(32)
CONTEXT:  COPY num, line 4, column dimh: "0xad66b56c81571b0e9d4882f564c06174"

[SQL: COPY NUM FROM '/home/ubuntu/notebooks/jan_num.csv'
CSV
HEADER;]
(Background on this error at: https://sqlalche.me/e/14/9h9h)


##### Error
The error we encountered whows the value is too long for type character varying(32), indicating that the data being inserted into the dimh column exceeds the maximum length defined for that column, which is 32 characters.

##### Next Step
Since the initial varchar(32) constraint was too short for some of the incoming data, so by increasing the length to 34 characters, we want to ensure that longer dimh values can be stored without causing errors during data loading. After running the command below, the dimh column will be able to store strings up to 34 characters long.

In [63]:
%%sql

ALTER TABLE NUM
ALTER COLUMN dimh TYPE varchar(34);

 * postgresql://student@/SECDB
Done.


[]

##### Load data again

In [64]:
%%sql

COPY NUM FROM '/home/ubuntu/notebooks/jan_num.csv'
CSV
HEADER;

 * postgresql://student@/SECDB
(psycopg2.errors.NumericValueOutOfRange) numeric field overflow
DETAIL:  A field with precision 2, scale 0 must round to an absolute value less than 10^2.
CONTEXT:  COPY num, line 283, column dcml: "-32768"

[SQL: COPY NUM FROM '/home/ubuntu/notebooks/jan_num.csv'
CSV
HEADER;]
(Background on this error at: https://sqlalche.me/e/14/9h9h)


##### Error
The error message refers to a column dcml defined as NUMERIC(2,0). The precision (2) allows a maximum of 2 digits. The scale (0) indicates no decimal places, meaning only whole numbers are permitted. The data includes a value -32768, which has five digits and is negative.
Since the column only allows values between -99 and 99 (absolute values within two digits), -32768 exceeds this limit, causing the overflow.

##### Next Step
To accommodate larger numbers, we increase the column’s precision to NUMERIC(5,0). This would allow values with up to five digits, which would include -32768.

In [65]:
%%sql

ALTER TABLE num
ALTER COLUMN dcml TYPE NUMERIC(5,0);

 * postgresql://student@/SECDB
Done.


[]

##### Load data again

In [66]:
%%sql

COPY NUM FROM '/home/ubuntu/notebooks/jan_num.csv'
CSV
HEADER;

 * postgresql://student@/SECDB
598843 rows affected.


[]

In [67]:
!wc -l /home/ubuntu/notebooks/jan_num.csv

598844 /home/ubuntu/notebooks/jan_num.csv


##### Data successfully loaded
598844 rows in jan_num.csv *including* the header for a total of 598843 rows of data. In table NUM, we see that there are also 598843 rows, validating that the counts of the csv match the counts in the database.

In [82]:
%%sql

ALTER TABLE NUM
ALTER COLUMN FOOTLEN TYPE NUMERIC(5,0);

 * postgresql://student@/SECDB
Done.


[]

In [83]:
%%sql

COPY NUM FROM '/home/ubuntu/notebooks/Assignment2/final_num.csv'
CSV
HEADER;

 * postgresql://student@/SECDB
(psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "num_pkey"
DETAIL:  Key (adsh, tag, version, ddate, qtrs, uom, dimh, iprx)=(0000002488-24-000012, AccountsPayableCurrent, us-gaap/2023, 2022-12-31, 0, USD, 0x00000000, 0) already exists.
CONTEXT:  COPY num, line 2

[SQL: COPY NUM FROM '/home/ubuntu/notebooks/Assignment2/jan_num.csv'
CSV
HEADER;]
(Background on this error at: https://sqlalche.me/e/14/gkpj)


In [33]:
%%sql

ALTER TABLE NUM
ALTER COLUMN VALUE TYPE NUMERIC(20,4);

 * postgresql://student@/SECDB
Done.


[]

In [9]:
%%sql

COPY NUM FROM '/home/ubuntu/notebooks/Assignment2/final_num.csv'
CSV
HEADER;

 * postgresql://student@/SECDB
(psycopg2.errors.NumericValueOutOfRange) numeric field overflow
DETAIL:  A field with precision 20, scale 4 must round to an absolute value less than 10^16.
CONTEXT:  COPY num, line 734836, column value: "75000000000000000.0000"

[SQL: COPY NUM FROM '/home/ubuntu/notebooks/final_num.csv'
CSV
HEADER;]
(Background on this error at: https://sqlalche.me/e/14/9h9h)


In [34]:
%%sql

ALTER TABLE NUM 
ALTER COLUMN VALUE TYPE NUMERIC(22);

 * postgresql://student@/SECDB
Done.


[]

In [ ]:
%%sql

COPY NUM FROM '/home/ubuntu/notebooks/Assignment2/final_num.csv'
CSV
HEADER;

 * postgresql://student@/SECDB


In [34]:
!wc -l /home/ubuntu/notebooks/Assignment2/jan_num.csv

598844 /home/ubuntu/notebooks/Assignment2/jan_num.csv


IF THE COMMAND ABOVE RUNS SUCCESSFULLY THEN PROCEED TO LOADING PRE

### Loading PRE dataset into the PRE table

In [68]:
%%sql

COPY PRE FROM '/home/ubuntu/notebooks/jan_pre.csv'
CSV
HEADER;

 * postgresql://student@/SECDB
(psycopg2.errors.NotNullViolation) null value in column "stmt" violates not-null constraint
DETAIL:  Failing row contains (0001828852-24-000024, 1, 22, null, f, AmendmentFlag, dei/2022, terseLabel, Amendment Flag, f).
CONTEXT:  COPY pre, line 2: "0001828852-24-000024,1,22,,0,AmendmentFlag,dei/2022,terseLabel,Amendment Flag,0"

[SQL: COPY PRE FROM '/home/ubuntu/notebooks/jan_pre.csv'
CSV
HEADER;]
(Background on this error at: https://sqlalche.me/e/14/gkpj)


##### Error:
Since stmt does have NULL values, it violates the not-null constraint. One approach to resolve this would be to fill in all the missing values based on the financial statement each row belongs to. However, we do not have access to the original XBRL submission data or documentation that specifies this information, so we cannot go forward with this approach.

##### Next Step
As per the documentation, the acceptable values for the column are: CP = Cover Page, BS = Balance Sheet, IS = Income Statement, CF = Cash Flow, EQ = Equity, CI = Comprehensive Income, and UN = Unclassifiable Statement. Since we're unsure which value applies to each row, we can use UN (Unclassifiable Statement) as a temporary default for rows where the specific financial statement is unknown. We would first remove the NOT NULL constraint and then once the data is loaded we will update the table.     

In [69]:
%%sql
ALTER TABLE PRE
ALTER COLUMN stmt DROP NOT NULL; 

 * postgresql://student@/SECDB
Done.


[]

##### Load the data again

In [70]:
%%sql

COPY PRE FROM '/home/ubuntu/notebooks/jan_pre.csv'
CSV
HEADER;

 * postgresql://student@/SECDB
(psycopg2.errors.NotNullViolation) null value in column "plabel" violates not-null constraint
DETAIL:  Failing row contains (0001185185-24-000066, 2, 31, BS, f, StockholdersEquityBeforeTreasuryStock, us-gaap/2023, totalLabel, null, f).
CONTEXT:  COPY pre, line 14418: "0001185185-24-000066,2,31,BS,0,StockholdersEquityBeforeTreasuryStock,us-gaap/2023,totalLabel,,0"

[SQL: COPY PRE FROM '/home/ubuntu/notebooks/jan_pre.csv'
CSV
HEADER;]
(Background on this error at: https://sqlalche.me/e/14/gkpj)


##### Error:
The "plabel" field provides descriptive labels for financial statement tags, but some values are missing, which violates the "not-null" rule.

##### Next Step
Normally, we’d try to find and fill in these missing values, but we don't have enough information from the documentation or the sponsor. However, since "plabel" is a string and mainly adds extra detail to each tag in the PRE table, it doesn't seem crucial for calculations, especially because the "tag" field itself is not null. This means that even if "plabel" is missing, we can still get the necessary information from "tag." Given that there are only 270 missing values in a large dataset, we decided to leave them as is by dropping the NULL constraint on it to load the data.

In [71]:
%%sql
ALTER TABLE PRE
ALTER COLUMN plabel DROP NOT NULL;

 * postgresql://student@/SECDB
Done.


[]

We created an ALTER TABLE statement for both the stmt and plabel attributes to change their constraints from NOT NULL to NULL. Although the financial statement specifies that these fields may not be null, our data analysis reveals actual null values in these columns. To address this discrepancy and avoid error messages, it's necessary to update the constraints accordingly.

In [72]:
%%sql

COPY PRE FROM '/home/ubuntu/notebooks/jan_pre.csv'
CSV
HEADER;

 * postgresql://student@/SECDB
511413 rows affected.


[]

In [73]:
!wc -l /home/ubuntu/notebooks/jan_pre.csv

511414 /home/ubuntu/notebooks/jan_pre.csv


##### Data sucessfully loaded:
511414 rows in jan_pre.csv *including* the header for a total of 511413 rows of data. In table PRE, we see that there are also 511413 rows, validating that the counts of the csv match the counts in the database.

##### Imputing values for stmt

To resolve the ERROR: column 'stmt' contains NULL values, which violates the NOT NULL constraint, we first have to figure out how many NULL values are there.
This (SELECT) command checks how many rows in the PRE table have NULL values in the stmt column. To do this, it selects the count of version, a column that has NO NULL values, where stmt is NULL. By counting version instead of stmt, we ensure each row is accounted for accurately, as using stmt would result in an output of "0 rows affected" due to the presence of NULL values. This approach gives us a clear count of rows in which stmt is missing data. After we run the code, we see that there are **"413897"** rows that are NULL in stmt.

In [74]:
%%sql
SELECT COUNT(version)
FROM PRE
WHERE stmt IS NULL;

 * postgresql://student@/SECDB
1 rows affected.


[(413897,)]

Secondly, since we determined that the best approach is to enter "UN" for the missing NULL values in the stmt column, we need to implement this. The UPDATE and SET command will update the stmt column and replace any NULL values with "UN." After running the code, we get the same result: **"413897"**, indicating that our command was successful and "UN" has been entered for all the missing values.

In [75]:
%%sql
UPDATE PRE
SET stmt = 'UN'
WHERE stmt IS NULL;

 * postgresql://student@/SECDB
413897 rows affected.


[]

To address our *second error, ERROR: column 'plabel' contains NULL values, which violates the NOT NULL constraint, we need to determine how many NULL values are present in that column. We will use the same method as before, referencing the version column in our SELECT command because the plabel column contains NULL values, which would result in "0 rows affected" if we used it directly. By replacing stmt with plabel in the command, we obtain an output of **87 count*. Since this is a small number, we have decided to leave it as is, as it has little significance, as previously explained.

In [76]:
%%sql
SELECT COUNT(version)
FROM PRE
WHERE plabel IS NULL;

 * postgresql://student@/SECDB
1 rows affected.


[(87,)]

## Part III: Data Analysis

### Queries:

##### Q1 
This question asks for information about submissions from the database. We need to formulate a query that selects specific columns to display:
"Submission ID": The unique identifier for each submission.
"Company Name": The name associated with company that made the submission.
"Submission Date": The date when the submission was filed.
"Mailing Address": The complete mailing address derived from concatenating the "MAS1", "CITYMA", "ZIPMA", and "COUNTRYMA" columns.
The query should filter the results to include submissions that fall into two specific Standard Industrial Classification (SIC) code ranges:
8000 to 8093: This range corresponds to Health Services.
3821 to 3873: This range corresponds to Medical Equipment and Supplies.

In [153]:
%%sql
SELECT ADSH as "Submission ID",
    NAME as "Name", 
    FILED as "Submission Date",
    MAS1 || ', ' || CITYMA || ' ' || ZIPMA || ', ' || COUNTRYMA as "Mailing Address"
FROM SUB
WHERE SIC BETWEEN 8000 AND 8093
    OR SIC BETWEEN 3821 AND 3873

 * postgresql://student@/SECDB
463 rows affected.


[('0000920148-24-000002', 'LABORATORY CORP OF AMERICA HOLDINGS', datetime.date(2024, 1, 2), '358 S MAIN ST, BURLINGTON 27215, US'),
 ('0000950170-24-000014', 'UNIVERSAL HEALTH SERVICES INC', datetime.date(2024, 1, 2), '367 S GULPH ROAD, KING OF PRUSSIA 19406, US'),
 ('0000950170-24-000306', 'OUTSET MEDICAL, INC.', datetime.date(2024, 1, 2), '3052 ORCHARD DRIVE, SAN JOSE 95134, US'),
 ('0001104659-24-000146', 'ORTHOPEDIATRICS CORP', datetime.date(2024, 1, 2), '2850 FRONTIER DRIVE, WARSAW 46582, US'),
 ('0001104659-24-000386', 'PRECIPIO, INC.', datetime.date(2024, 1, 2), '4 SCIENCE PARK, NEW HAVEN 06511, US'),
 ('0001193125-24-000620', 'AKUMIN INC.', datetime.date(2024, 1, 2), '8300 W SUNRISE BLVD, PLANTATION 33322, US'),
 ('0001193125-24-000684', 'TRANSMEDICS GROUP, INC.', datetime.date(2024, 1, 2), '200 MINUTEMAN ROAD, ANDOVER 01810, US'),
 ('0001213900-24-000317', 'BLUEJAY DIAGNOSTICS, INC.', datetime.date(2024, 1, 2), '360 MASSACHUSETTS AVENUE, SUITE 203, ACTON 01720, US'),
 ('0001437749-24-000113', 'PULSE BIOSCIENCES, INC.', datetime.date(2024, 1, 2), '3957 POINT EDEN WAY, HAYWARD 94545, US'),
 ('0001493152-23-046641', 'MANGOCEUTICALS, INC.', datetime.date(2024, 1, 2), '15110 DALLAS PKWY, SUITE 600, DALLAS 75248, US'),
 ('0001493152-24-000035', 'DAXOR CORP', datetime.date(2024, 1, 2), '350 5TH AVENUE, NEW YORK 10118, US'),
 ('0001493152-24-000071', 'GLUCOTRACK, INC.', datetime.date(2024, 1, 2), '301 RT 17 NORTH, RUTHERFORD 07070, US'),
 ('0001493152-24-000083', 'AGAPE ATP CORP', datetime.date(2024, 1, 2), '1705-1708 LEVEL 17, TOWER 2, FABER TOWER, KUALA LUMPUR 58100, MY'),
 ('0001493152-24-000109', 'MICROBOT MEDICAL INC.', datetime.date(2024, 1, 2), '25 RECREATION PARK DR SUITE 108, HINGHAM 02043, US'),
 ('0001493152-24-000132', 'BONE BIOLOGICS CORP', datetime.date(2024, 1, 2), '2 BURLINGTON WOODS DRIVE,, BURLINGTON 01803, US'),
 ('0001683168-24-000004', 'MEDICALE CORP.', datetime.date(2024, 1, 2), '9314 FOREST HILL BLVD, WELLINGTON 33411, US'),
 ('0000950170-24-000544', 'ALPHATEC HOLDINGS, INC.', datetime.date(2024, 1, 3), '5818 EL CAMINO REAL, CARLSBAD 92008, US'),
 ('0001079973-24-000004', 'NEMAURA MEDICAL INC.', datetime.date(2024, 1, 3), '57 WEST 57TH STREET, MANHATTAN 10019, US'),
 ('0001079973-24-000007', 'PRO DEX INC', datetime.date(2024, 1, 3), '2361 MCGAW AVENUE, IRVINE 92614, US'),
 ('0001079973-24-000008', 'NEMAURA MEDICAL INC.', datetime.date(2024, 1, 3), '57 WEST 57TH STREET, MANHATTAN 10019, US'),
 ('0001104659-24-000868', 'INVIVO THERAPEUTICS HOLDINGS CORP.', datetime.date(2024, 1, 3), 'ONE KENDALL SQUARE, CAMBRIDGE 02139, US'),
 ('0001104659-24-000906', 'ASSURE HOLDINGS CORP.', datetime.date(2024, 1, 3), '7887 EAST BELLEVIEW AVENUE, GREENWOOD VILLAGE 80111, US'),
 ('0001104659-24-000910', 'ASSURE HOLDINGS CORP.', datetime.date(2024, 1, 3), '7887 EAST BELLEVIEW AVENUE, GREENWOOD VILLAGE 80111, US'),
 ('0001140361-24-000342', 'STRATA SKIN SCIENCES, INC.', datetime.date(2024, 1, 3), '5 WALNUT GROVE DRIVE, HORSHAM 19044, US'),
 ('0001140361-24-000483', 'SANUWAVE HEALTH, INC.', datetime.date(2024, 1, 3), '3360 MARTIN FARM RD, SUWANEE 30024, US'),
 ('0001193125-24-000976', 'ENOVIS CORP', datetime.date(2024, 1, 3), '2711 CENTERVILLE ROAD, WILMINGTON 19808, US'),
 ('0001193125-24-001477', 'COGNEX CORP', datetime.date(2024, 1, 3), 'ONE VISION DRIVE, NATICK 01760, US'),
 ('0001437749-24-000290', 'PERSPECTIVE THERAPEUTICS, INC.', datetime.date(2024, 1, 3), '2401 ELLIOTT AVENUE, SEATTLE 98121, US'),
 ('0001477932-24-000016', 'HAWKEYE SYSTEMS, INC.', datetime.date(2024, 1, 3), '6605 ABERCORN, SAVANNAH 31405, US'),
 ('0001493152-24-000338', 'INVO BIOSCIENCE, INC.', datetime.date(2024, 1, 3), '5582 BROADCAST COURT, SARASOTA 34240, US'),
 ('0001493152-24-000339', 'ENDONOVO THERAPEUTICS, INC.', datetime.date(2024, 1, 3), '6320 CANOGA AVENUE, WOODLAND HILLS 91367, US'),
 ('0000805928-24-000005', 'AXOGEN, INC.', datetime.date(2024, 1, 4), '13631 PROGRESS BLVD., ALACHUA 32615, US'),
 ('0000950157-24-000024', 'ILLUMINA, INC.', 

##### Q2
This question asks for the following:
Extract the month from the "FILED" date column.
Counts the number of unique submissions (ADSH values) for each month.
Group the results by month, creating a summary table that shows the total number of submissions per month. 

Since we were only able to load in one month of data the query would just have the total number of submissions and not the average.

In [78]:
%%sql
SELECT EXTRACT(MONTH FROM FILED) as "Month",
    COUNT(ADSH) as "Total Number of Submissions"
FROM SUB
GROUP BY EXTRACT(MONTH FROM FILED);

 * postgresql://student@/SECDB
1 rows affected.


[(1.0, 5904)]

##### Q3
This question asks to identify and rank the most common tags associated with companies in the Finance and Insurance sector (SIC codes 6021-6411). We filter for companies in the finance sector and ensures each has a relevant tag in the NUM table. By retrieving each tag's ID, label (name), and counting distinct companies (cik) linked to each tag, the query provides the number of unique companies associated with each tag. Grouping by tag ID and label, it then orders the results by the company count in descending order, highlighting the most frequently associated tags in this sector at the top of the list.

In [79]:
%%sql
SELECT 
    TAG.tag as "Tag ID", 
    TAG.tlabel as "Tag Label", 
    COUNT(DISTINCT SUB.cik) AS "Total Companies"
FROM TAG, SUB, NUM
WHERE
    TAG.tag = NUM.tag
    AND SUB.adsh = NUM.adsh
    AND SUB.sic BETWEEN 6021 AND 6411           
GROUP BY 
    TAG.tag, 
    TAG.tlabel                              
ORDER BY 
    "Total Companies" DESC;

 * postgresql://student@/SECDB
2773 rows affected.


[('NetIncomeLoss', 'Net loss', 18),
 ('NetIncomeLoss', 'Net Income (Loss) Attributable to Parent', 18),
 ('Liabilities', 'Liabilities', 17),
 ('Assets', 'Assets', 17),
 ('StockholdersEquity', 'Equity, Attributable to Parent', 15),
 ('LiabilitiesAndStockholdersEquity', 'Liabilities and Equity', 15),
 ('NetCashProvidedByUsedInOperatingActivities', 'Net Cash Provided by (Used in) Operating Activities', 15),
 ('StockholdersEquity', "Stockholders' Equity Attributable to Parent", 15),
 ('CommonStockSharesOutstanding', 'Common stock, shares outstanding', 14),
 ('RetainedEarningsAccumulatedDeficit', 'Accumulated deficit', 14),
 ('RetainedEarningsAccumulatedDeficit', 'Retained Earnings (Accumulated Deficit)', 14),
 ('CommonStockSharesOutstanding', 'Common Stock, Shares, Outstanding', 14),
 ('CommonStockParOrStatedValuePerShare', 'Common Stock, Par or Stated Value Per Share', 14),
 ('NetCashProvidedByUsedInFinancingActivities', 'Net Cash Provided by (Used in) Financing Activities', 14),
 ('CommonStockParOrStatedValuePerShare', 'Common stock, par value', 14),
 ('CommonStockSharesIssued', 'Common stock, shares issued', 13),
 ('CommonStockSharesIssued', 'Common Stock, Shares, Issued', 13),
 ('CashAndCashEquivalentsAtCarryingValue', 'Cash and Cash Equivalents, at Carrying Value', 13),
 ('CommonStockValue', 'Common stock, $0.001 par value; 100,000,000 and 50,000,000 shares authorized as of December 31, 2022 and December 31, 2021; 15,193,587 and 13,466,603 ... (31 characters truncated) ... 1, 2022 and December 31, 2021, respectively; 15,166,596 and 13,439,612 shares outstanding as of December 31, 2022 and December 31, 2021, respectively', 13),
 ('CommonStockValue', 'Common Stock, Value, Issued', 13),
 ('CommonStockSharesAuthorized', 'Common stock, shares authorized', 12),
 ('EntityCommonStockSharesOutstanding', 'Entity Common Stock, Shares Outstanding', 12),
 ('NetCashProvidedByUsedInInvestingActivities', 'Net Cash Provided by (Used in) Investing Activities', 12),
 ('CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalents', 'Cash, Cash Equivalents, Restricted Cash, and Restricted Cash Equivalents', 12),
 ('CommonStockSharesAuthorized', 'Common Stock, Shares Authorized', 12),
 ('CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalents', '[Cash and cash equivalents, beginning of year]', 12),
 ('InterestExpense', 'Interest Expense', 11),
 ('IncomeTaxExpenseBenefit', 'Income Tax Expense (Benefit)', 11),
 ('InterestExpense', 'Interest expense', 11),
 ('WeightedAverageNumberOfDilutedSharesOutstanding', 'Weighted Average Number of Shares Outstanding, Diluted', 10),
 ('WeightedAverageNumberOfSharesOutstandingBasic', 'Weighted Average Number of Shares Outstanding, Basic', 10),
 ('EarningsPerShareBasic', 'Earnings Per Share, Basic', 10),
 ('EarningsPerShareDiluted', 'Earnings Per Share, Diluted', 10),
 ('InterestPaidNet', 'Cash paid for interest', 10),
 ('ShareBasedCompensation', 'Share-based compensation', 10),
 ('ShareBasedCompensation', 'Share-Based Payment Arrangement, Noncash Expense', 10),
 ('PreferredStockSharesAuthorized', 'Preferred Stock, Shares Authorized', 10),
 ('PreferredStockSharesAuthorized', 'Preferred stock, shares authorized', 10),
 ('OperatingExpenses', 'Operating Expenses', 10),
 ('InterestPaidNet', 'Interest Paid, Excluding Capitalized Interest, Operating Activities', 10),
 ('PreferredStockValue', 'Preferred Stock, Value, Issued', 10),
 ('PreferredStockParOrStatedValuePerShare', 'Preferred stock, par value', 10),
 ('PreferredStockParOrStatedValuePerShare', 'Preferred Stock, Par or Stated Value Per Share', 10),
 ('PreferredStockSharesOutstanding', 'Preferred stock, shares outstanding', 9),
 ('AccumulatedOtherComprehensiveIncomeLossNetOfTax', 'Accumulated Other Comprehensive Income (Loss), Net of Tax', 9),
 ('AccumulatedOtherComprehensiveIncomeLossNetOfTax', 'Accumulated other comprehensive income', 9),
 ('CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalentsPeriodIncreaseDecreaseIncludingExchangeRateEffect', 'Cas

##### Q4
The question asks to retrieve the top 5 companies with the highest total assets in 2024, displaying each company's name, sector, and the count of unique tags in their filings. The query we use joins the SUB, NUM, and TAG tables to access company details, asset values, and tags, then calculates total assets by summing values where the tag has "Assets" in it. We group it by company name and sector. The query then orders results by total assets in descending order and limits the output to the top 5 companies.

In [80]:
%%sql
SELECT 
    SUB.name AS "Company Name", 
    SUB.sic AS "Sector", 
    COUNT(DISTINCT TAG.tag) AS "Unique Tags Used",
    SUM(CASE WHEN TAG.tag = 'Assets' THEN NUM.value ELSE 0 END) AS "Total Assets"
FROM  
    SUB
JOIN 
    NUM ON SUB.adsh = NUM.adsh
JOIN 
    TAG ON NUM.tag = TAG.tag AND NUM.version = TAG.version
GROUP BY 
    SUB.name, 
    SUB.sic
ORDER BY 
    "Total Assets" DESC                  
LIMIT 5;

 * postgresql://student@/SECDB
5 rows affected.


[('ECOPETROL S.A.', Decimal('1311'), 384, Decimal('924163282000000')),
 ('AMERICA MOVIL SAB DE CV/', Decimal('4813'), 246, Decimal('9655132705000')),
 ('GENERAL MOTORS CO', Decimal('3711'), 473, Decimal('2741695000000')),
 ('MICROSOFT CORP', Decimal('7372'), 249, Decimal('882534000000')),
 ('BOEING CO', Decimal('3721'), 540, Decimal('822336000000'))]